Repository tektoncd/plumbing, pull requests merged in 2019-07, with the labels that each got.

#40 Add experimental postsubmit to publish images
  prow/config.yaml
Labels: approved, lgtm, size/M

#41 Add tektoncd/triggers repository to prow
  prow/config.yaml
Labels: approved, lgtm, size/L

#42 Add postsubmits jobs for coverage…
  prow/config.yaml
Labels: approved, lgtm, size/M

#45 Moveci-tekton-pipeline-nightly-release to postsubmit
  prow/config.yaml
Labels: approved, lgtm, size/M

#46 Add tektoncd/operator to the prow configuration.
  prow/config.yaml
Labels: approved, lgtm, size/L

#47 Fix typo for tektoncd/pipeline postsubmit job 🙀
  prow/config.yaml
Labels: approved, lgtm, size/XS

#48 Enable friends repository in tide.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#49 Catch tabs vs spaces with gofmt presubmit linting
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#50 Add 2 labels : area/release and area/dogfooding
  label_sync/labels.yaml
Labels: approved, lgtm, size/S

#51 Update test-runner image to a recent version 👼
  Makefile
  prow/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS
