Repository tektoncd/plumbing, pull requests merged in 2019-11, with the labels that each got.

#106 Accept UUID as well as Prow-format Build IDs
  pipelinerun-logs/cmd/http/query.go
  pipelinerun-logs/cmd/http/query_test.go
  pipelinerun-logs/cmd/http/server.go
  pipelinerun-logs/cmd/http/server_test.go
Labels: approved, lgtm, size/L

#105 Add script for setting up GCP project permissions 🔒
  README.md
  addpermissions.py
Labels: approved, lgtm, size/M

#107 Add UUID to image build jobs
  tekton/config/README.md
  tekton/config/nightly-image-build-cron-base/trigger-image-build.yaml
  tekton/config/tkn-image-nightly-build-cron/cronjob.yaml
  tekton/resources/image-build-trigger.yaml
Labels: approved, lgtm, size/S

#104 As `cmd/{bash,nop,gsutil}` image are gone, removing them from plumbing ⛏
  prow/config.yaml
  tekton/resources/pipeline-nightly-build-trigger.yaml
Labels: approved, lgtm, size/S

#101 Add a beta-blocking label to tektoncd/pipeline
  label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#100 Configure stackdriver access for pipelinerun-logs app
  pipelinerun-logs/README.md
  pipelinerun-logs/config/deployment.yaml
Labels: approved, lgtm, size/S

#111 Add yamllint to the test-runner image and scripts 📦
  prow/images/test-runner/Dockerfile
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#114 Bump prow job to latest dogfooding test-runner image 🐯
  prow/config.yaml
Labels: approved, lgtm, size/M

#115 Fix yaml_build_tests 😅
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#112 Linting yamls with yamllint 🏷
  .yamllint
  boskos/boskos-config.yaml
  boskos/boskos.yaml
  gubernator/config.yaml
  label_sync/labels.yaml
  prow/ingress.yaml
  tekton/config/nightly-image-build-cron-base/trigger-image-build.yaml
  tekton/config/nightly-release-cron-base/trigger-with-uuid.yaml
  tekton/resources/install_tekton_release.yaml
Labels: approved, lgtm, size/M

#116 No-op for yamllint if no yaml files got changed
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#110 Add a Task definition and TaskRun to use peribolos to sync github per…
  README.md
  tekton/README.md
  tekton/resources/org-permissions/peribolos-run.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
  tekton/resources/org-permissions/peribolos.yaml
Labels: approved, lgtm, ok-to-test, size/L

#120 Add quotes to fix the pipelinerun logs app deployment
  pipelinerun-logs/config/deployment.yaml
Labels: approved, lgtm, size/XS

#119 Allow logs from multiple namespaces
  pipelinerun-logs/README.md
  pipelinerun-logs/cmd/http/server.go
  pipelinerun-logs/cmd/http/server_test.go
  pipelinerun-logs/go.mod
  pipelinerun-logs/go.sum
  pipelinerun-logs/pkg/config/config.go
Labels: approved, lgtm, size/L

#131 Make image build runs more discoverable
  tekton/config/nightly-image-build-cron-base/trigger-image-build.yaml
  tekton/resources/image-build-trigger.yaml
Labels: approved, lgtm, size/L

#133 Fixes after PR#131
  tekton/config/nightly-image-build-cron-base/trigger-image-build.yaml
  tekton/resources/image-build-trigger.yaml
Labels: approved, lgtm, size/M

#129 Install a pinned stable version of golangci-lint instead of master
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/S

#130 Add a image with `hub` and a nightly build job
  tekton/config/hub-image-nightly-build-cron/cronjob.yaml
  tekton/config/hub-image-nightly-build-cron/kustomization.yaml
  tekton/images/hub/Dockerfile
Labels: approved, lgtm, size/M

#132 Use tag latest for test-runner instead of a digest 😅
  prow/config.yaml
Labels: approved, lgtm, size/M
