Repository tektoncd/plumbing, pull requests merged in 2019-06, with the labels that each got.

#33 Additional revert dep-collector repository path to knative.
  scripts/library.sh
Labels: approved, lgtm, size/XS

#32 Add a label_sync folder with tekton labels…
  label_sync/README.md
  label_sync/cluster/label_sync_cron_job.yaml
  label_sync/cluster/label_sync_job.yaml
  label_sync/labels.yaml
Labels: approved, lgtm, size/XL

#35 Double the number of boskos projects 📈
  README.md
  boskos/boskos-config.yaml
Labels: approved, lgtm, size/S

#37 Add a CI on tektoncd/experimental…
  prow/config.yaml
Labels: approved, lgtm, size/L

#36 Fix label_sync file and README
  label_sync/README.md
  label_sync/labels.yaml
Labels: approved, lgtm, size/M

#38 Add a missing step to the boskos documentation on adding a new project.
  README.md
Labels: approved, lgtm, size/XS

#39 Rollback the coverage image to the last tag.
  prow/config.yaml
Labels: approved, lgtm, size/XS
