Repository tektoncd/plumbing, pull requests merged in 2019-10, with the labels that each got.

#77 Fix tektoncd/pipeline upgrade tests periodics job 🍂
  prow/config.yaml
Labels: approved, lgtm, size/XS

#78 Fix tektoncd/pipeline upgrade tests periodics job : no decorate 🍂
  prow/config.yaml
Labels: approved, lgtm, size/XS

#76 Add an app to expose PipelneRun logs publicly
  pipelinerun-logs/README.md
  pipelinerun-logs/cmd/http/entry.go
  pipelinerun-logs/cmd/http/main.go
  pipelinerun-logs/cmd/http/query.go
  pipelinerun-logs/cmd/http/query_test.go
  pipelinerun-logs/cmd/http/server.go
  pipelinerun-logs/go.mod
  pipelinerun-logs/go.sum
  pipelinerun-logs/pkg/config/config.go
  pipelinerun-logs/pkg/config/config_test.go
  pipelinerun-logs/templates/entries.html
Labels: approved, lgtm, size/XL

#82 Add a dockerfile and deployment description for pipelinerun-logs
  pipelinerun-logs/Dockerfile
  pipelinerun-logs/deployment.yaml
Labels: approved, lgtm, size/M

#73 Add a pipeline to deploy and test a release of a Tekton project
  scripts/library.sh
  scripts/logs/README.md
  scripts/logs/color/color.go
  scripts/logs/kodata/LICENSE
  scripts/logs/kodata/VENDOR-LICENSE
  scripts/logs/main.go
  scripts/logs/pipelinerun/logs.go
  scripts/logs/pod/watcher.go
  scripts/logs/taskrun/logs.go
  tekton/README.md
  tekton/install_and_test_tekton_release.yaml
  tekton/install_tekton_release.yaml
  tekton/test_tekton_release.yaml
Labels: approved, lgtm, size/XXL

#84 Add a task for preprelease checks
  tekton/prerelease_checks.yaml
Labels: approved, lgtm, size/M

#88 Update test-runner image to use go 1.13
  prow/images/test-runner/Dockerfile
Labels: approved, lgtm, size/S

#89 Deploy pipelinerun-logs with ko
  pipelinerun-logs/README.md
  pipelinerun-logs/cmd/http/main.go
  pipelinerun-logs/cmd/http/server.go
  pipelinerun-logs/config/deployment.yaml
  pipelinerun-logs/go.mod
Labels: approved, lgtm, size/S

#91 Fix the ko deployment for the logs app
  pipelinerun-logs/README.md
  pipelinerun-logs/cmd/http/kodata/templates
  pipelinerun-logs/cmd/http/main.go
  pipelinerun-logs/config/deployment.yaml
  pipelinerun-logs/go.mod
  pipelinerun-logs/go.sum
Labels: approved, lgtm, size/L

#93 Bump test-runner image to latest built 🏗
  prow/config.yaml
Labels: approved, lgtm, size/M

#94 Use tkn instead of custom log logger
  scripts/library.sh
  scripts/logs/README.md
  scripts/logs/color/color.go
  scripts/logs/kodata/LICENSE
  scripts/logs/kodata/VENDOR-LICENSE
  scripts/logs/main.go
  scripts/logs/pipelinerun/logs.go
  scripts/logs/pod/watcher.go
  scripts/logs/taskrun/logs.go
Labels: approved, lgtm, size/XXL

#96 test-runner: install githubhelper in the PATH
  prow/images/test-runner/Dockerfile
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#97 Bump test-runner image to latest version
  prow/config.yaml
Labels: approved, lgtm, size/M

#99 Add go-coverage jobs to the triggers project
  prow/config.yaml
Labels: approved, lgtm, size/M
