Repository tektoncd/plumbing, pull requests merged in 2019-08, with the labels that each got.

#53 tektoncd/operator integration tests needs a Docker socket…
  prow/config.yaml
Labels: approved, lgtm, size/XS

#55 Add configuration and docs on how to update Prow 
  README.md
  prow/config.yaml
  prow/prow.yaml
Labels: approved, lgtm, size/XL

#59 Add a build-cross-tests job to the cli 🏗
  prow/config.yaml
Labels: approved, lgtm, size/M

#61 tektoncd/pipeline postsubmit job needs docker socket access
  prow/config.yaml
Labels: approved, lgtm, size/XS

#67 Put securityContext on the right place for tektoncd/pipeline postsubmit
  prow/config.yaml
Labels: approved, lgtm, size/XS

#68 Add docs on how to create a new Prow cluster ✨
  boskos/boskos.yaml
  gcp.md
  prow/README.md
Labels: approved, lgtm, size/L
