Repository tektoncd/plumbing, pull requests merged in 2019-09, with the labels that each got.

#56 Add the prow job to test the upgrade 🧗‍♂️
  prow/config.yaml
Labels: approved, lgtm, size/M

#70 Add afrittoli and dibyom to owners
  OWNERS
Labels: approved, lgtm, size/XS

#72 Remove implicit self approve
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#74 Remove unused start_latest_tekton_serving
  scripts/library.sh
Labels: approved, lgtm, size/S
