Repository tektoncd/plumbing, pull requests merged in 2019-04, with the labels that each got.

#2 Move test infrastructure to this repo 🚚
  .github/issue-template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  OWNERS
  README.md
  boskos/boskos-config.yaml
  boskos/boskos.yaml
  boskos/storage-class.yaml
  code-of-conduct.md
  gubernator/config.yaml
  prow/config.yaml
  prow/ingress.yaml
  prow/plugins.yaml
Labels: lgtm, size/XL

#4 Add tide to all tektoncd repos 🌊
  README.md
  prow/config.yaml
Labels: approved, lgtm, size/S

#5 Initial Prow configuration for tektoncd/dashboard repository
  prow/config.yaml
Labels: approved, lgtm, size/M

#7 Order tide repositories alphabetically 👼
  prow/config.yaml
Labels: approved, lgtm, size/XS

#6 Initial Prow configuration for tektoncd/cli repository
  prow/config.yaml
Labels: approved, lgtm, size/L

#8 Add merge_method to all repositories 👼
  prow/config.yaml
Labels: approved, lgtm, size/XS

#9 Add the catalog repo to tide.
  prow/config.yaml
Labels: approved, lgtm, size/XS
