Repository tektoncd/plumbing, pull requests merged in 2019-12, with the labels that each got.

#136 Fix release automation
  tekton/resources/release/github_release.yaml
Labels: approved, lgtm, size/S

#135 Add the letsencrypt cert-manager configs.
  prow/clusterissuer.yaml
  prow/ingress.yaml
Labels: approved, lgtm, size/S

#139 Add documentation for resources under tekton/
  tekton/README.md
  tekton/images/README.md
  tekton/resources/org-permissions/README.md
  tekton/resources/release/README.md
Labels: approved, lgtm, size/XL

#140 More documents on tekton resources
  tekton/README.md
  tekton/resources/README.md
Labels: approved, lgtm, size/S

#141 Use tektoncd CLI 0.5.1
  tekton/images/tkn/Dockerfile
Labels: approved, lgtm, size/XS

#142 Do pipeline nightly releases with Tekton only
  prow/config.yaml
  tekton/resources/pipeline-nightly-release/pipeline-nightly-build-trigger.yaml
Labels: approved, lgtm, size/M

#143 Add a `ko` image to the nightly build images 🌃
  tekton/config/ko-image-nightly-build-cron/cronjob.yaml
  tekton/config/ko-image-nightly-build-cron/kustomization.yaml
  tekton/images/ko/Dockerfile
Labels: approved, lgtm, size/M

#144 Write changed files to file instead of storing in a global var.
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#146 Use module aware tools based on go.mod, not vendor.
  scripts/library.sh
Labels: approved, lgtm, size/S

#147 Add Tekton to the list in the main README
  README.md
Labels: approved, lgtm, size/XS

#148 Fix the pipeline nightly release
  tekton/resources/pipeline-nightly-release/pipeline-nightly-build-trigger.yaml
Labels: approved, lgtm, size/XS

#151 Add a ko-gcloud image
  tekton/config/ko-gcloud-image-nightly-build-cron/cronjob.yaml
  tekton/config/ko-gcloud-image-nightly-build-cron/kustomization.yaml
  tekton/images/ko-gcloud/Dockerfile
Labels: approved, lgtm, size/M

#153 Add license and maintaner to the ko image
  tekton/images/ko-gcloud/Dockerfile
Labels: approved, lgtm, size/S

#152 Fix ingress annotation and cert-manager configuration 👼
  prow/clusterissuer.yaml
  prow/ingress.yaml
Labels: approved, lgtm, size/XS

#154 Hopefully disable the markdown link checker
  prow/config.yaml
Labels: approved, lgtm, size/XS

#155 tkn version 0.6.0
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS

#149 Refactor pipeline nightly-release into an kustomize overlay.
  tekton/resources/nightly-release/base/bindings.yaml
  tekton/resources/nightly-release/base/eventlistener.yaml
  tekton/resources/nightly-release/base/kustomization.yaml
  tekton/resources/nightly-release/base/kustomizeconfig/eventlistener.yaml
  tekton/resources/nightly-release/base/serviceaccount.yaml
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/bindings.yaml
  tekton/resources/nightly-release/overlays/pipeline/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/pipeline-nightly-release/pipeline-nightly-build-trigger.yaml
Labels: approved, lgtm, size/L

#118 Setup a mario bot to build images on demand
  cmd/mario/kodata/LICENSE
  cmd/mario/kodata/OWNERS
  cmd/mario/main.go
  config/100-namespace.yaml
  config/200-serviceaccount.yaml
  config/mario.yaml
  pipelinerun-logs/config/deployment.yaml
  tekton/resources/mario-github-comment.yaml
  tekton/resources/mario-image-build-trigger.yaml
Labels: approved, lgtm, size/XL

#156 Add Kustomize to ko and ko-gcloud images
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
Labels: approved, lgtm, size/XS

#161 Fix area/dogfooding label 🌮
  label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#163 Deploy Tekton services from release with overlay
  tekton/cd/pipeline/base/kustomization.yaml
  tekton/cd/pipeline/overlays/dogfooding/config-artifact-bucket.yaml
  tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
  tekton/resources/release/install_tekton_release.yaml
Labels: approved, lgtm, size/L

#164 Update Version to 0.6.0 for tkn Image
  tekton/images/tkn/Dockerfile
Labels: approved, lgtm, size/XS

#162 Fix rotation.csv
  buildbot/rotation.csv
Labels: approved, lgtm, size/L

#166 ko-gcloud: fix typo, missing " 😅
  tekton/config/ko-gcloud-image-nightly-build-cron/kustomization.yaml
Labels: approved, lgtm, size/XS

#167 An EnvVar needs to be a string otherwise prow fails 😟
  prow/config.yaml
Labels: approved, lgtm, size/XS

#168 Remove build cops during christmas break 🎅
  buildbot/rotation.csv
Labels: approved, lgtm, size/S

#170 Make labels a bit easier for build cops 👮‍♀️
  label_sync/labels.yaml
Labels: approved, lgtm, size/L, ¯\_(ツ)_/¯

#173 Bump go to 1.13.5 🆙
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS
