Repository tektoncd/plumbing, pull requests merged in 2019-05, with the labels that each got.

#10 import knative/test-infra scripts in here
  scripts/README.md
  scripts/dummy.go
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/markdown-link-check-config.rc
  scripts/markdown-lint-config.rc
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#11 Add tests for the catalog repo.
  prow/config.yaml
Labels: approved, lgtm, size/L

#12 Fix the catalog tests.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#14 Rename tekton-cli-unit-tests to pull-tekton-cli-unit-tests
  prow/config.yaml
Labels: approved, lgtm, size/XS

#15 Add an extra_initialization step before running tests
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#18 Remove context from presubmit configuration
  prow/config.yaml
Labels: approved, lgtm, size/S

#19 Add a directory to hold image build configurations for use in our CI.
  Makefile
  prow/images/README.md
  prow/images/test-runner/Dockerfile
Labels: approved, lgtm, size/M

#16 Refactor dashboard config to use plumbing script
  prow/config.yaml
Labels: approved, lgtm, size/M

#20 Use the newly built image in prow CI.
  prow/config.yaml
Labels: approved, lgtm, size/S

#17 Add coverage build on cli
  prow/config.yaml
Labels: approved, lgtm, size/M

#21 Remove the latest `context` from presubmit
  prow/config.yaml
Labels: approved, lgtm, size/XS

#22 Make sure all jobs uses tekton-releases/tests/test-runner
  prow/config.yaml
Labels: approved, lgtm, size/XS

#24 Add the boskos configuration and update images.
  boskos/boskos-config.yaml
  boskos/boskos.yaml
Labels: approved, lgtm, size/L

#23 Add a postsubmits to dashboard to push nightly images
  prow/config.yaml
Labels: approved, lgtm, size/M

#27 Add a periodic job for pipeline 🕙
  prow/config.yaml
Labels: approved, lgtm, size/M

#30 Fix Tekton GitHub org name in scripts/library.sh
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#31 Revert dep-collector repository path to knative.
  scripts/library.sh
Labels: approved, lgtm, size/XS
