Repository tektoncd/plumbing, pull requests merged in 2020-12, with the labels that each got.

#652 [experimental] Enable dind for integration tests.
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/XS

#654 Add prow configs for tektoncd/results.
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/M

#658 Changes RBAC for triggers v0.10.1
  tekton/ci/0001_rbac.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/cd/kustomization.yaml
  tekton/resources/cd/serviceaccount.yaml
Labels: approved, kind/misc, lgtm, size/M

#656 Update dogfooding.md
  docs/dogfooding.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#660 Bump ko to 0.6.2 on CI images
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#659 Add HPA and disruption budget to tekton-admin
  robocat/cadmin/200-rbac.yaml
Labels: approved, kind/misc, lgtm, size/XS

#666 Tekton CLI 0.15.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#667 Update infra monitoring role name to buildcaptain
  bots/buildbot/README.md
  bots/buildbot/cmd/buildbot/main.go
  bots/buildbot/cmd/buildbot/rotation.go
  bots/buildbot/cmd/buildbot/rotation_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#668 Bump buildx version to the latest one
  tekton/images/buildx-gcloud/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#665 Add missing ko prefix to image
  tekton/ci/interceptors/add-pr-body/config/add-pr-body.yaml
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS

#669 Switch the minio chart repo to minio own one
  tekton/cronjobs/robocat/helm/minio-nightly/cronjob.yaml
Labels: approved, kind/misc, lgtm, size/XS

#657 Update README.md
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#671 Add a cronjob to deploy cronjobs that target robocat
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-robocat/README.md
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-robocat/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-robocat/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/M
