Repository tektoncd/plumbing, pull requests merged in 2020-07, with the labels that each got.

#450 Temporarly remove quotes from label description
  label_sync/labels.yaml
Labels: approved, kind/misc, lgtm, size/XS

#448 prow: add release-note plugin to cli 🐰
  prow/plugins.yaml
Labels: approved, kind/misc, lgtm, size/XS

#451 hub: add privileged to more hub jobs…
  prow/config.yaml
  tekton/images/test-runner/runner.sh
Labels: approved, kind/misc, lgtm, size/XS

#455 Don't send daily ping if there is no buildcop
  buildbot/cmd/buildbot/main.go
Labels: approved, kind/misc, lgtm, size/XS

#458 Setup the initial infra for dogfooding events
  tekton/cd/pipeline/overlays/dogfooding/config-defaults.yaml
  tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
  tekton/resources/cd/bindings.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/notification-template.yaml
  tekton/resources/kustomization.yaml
Labels: approved, kind/feature, lgtm, size/M

#459 Fix release deployment
  tekton/cronjobs/ko-gcloud-image-nightly-build-cron/README.md
  tekton/images/ko-gcloud/Dockerfile
  tekton/resources/release/install_tekton_release.yaml
Labels: approved, kind/bug, lgtm, size/S

#427 Bump ko version in ko-gcloud to v0.5.1 from v0.5.0
  tekton/images/ko-gcloud/Dockerfile
Labels: approved, kind/bug, lgtm, size/XS

#453 prow: enable release-note plugin on operator
  prow/plugins.yaml
Labels: approved, kind/misc, lgtm, size/XS

#457 Add Nikhil Thomas and Savita Ashture as buildcops…
  buildbot/README.md
  buildbot/rotation.csv
Labels: approved, kind/misc, lgtm, size/L

#432 Add dashboard integration tests with different pipelines versions
  prow/config.yaml
Labels: approved, kind/feature, lgtm, size/M

#462 Remove emails from script example
  addpermissions.py
Labels: approved, kind/cleanup, lgtm, size/XS

#464 Fix dashboard prow jobs
  prow/config.yaml
Labels: approved, kind/bug, lgtm, size/S

#446 Add needs-rebase deployment 🙃
  prow/prow.yaml
Labels: approved, kind/misc, lgtm, size/M

#452 prow: add postgres sidecar and remove dind for hub
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/M

#466 Revert "prow: add postgres sidecar and remove dind for hub"
  prow/config.yaml
Labels: approved, kind/bug, lgtm

#468 Hub: remove DIND and privileged securityContext
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/S

#473 Reduce dashboard integration tests combinations
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/L

#475 Update link to boskos docs
  boskos/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#476 Fix check name for tekton-golang-lint
  tekton/ci/plumbing-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#467 Setup slack notifications for failed configmap deploys
  tekton/resources/cd/bindings.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/notification-template.yaml
Labels: approved, kind/feature, lgtm, size/M

#474 Stop using cloud events pipeline resource in CI
  tekton/ci/bindings.yaml
  tekton/ci/checks/check-pr-has-kind-label.yaml
  tekton/ci/eventlistener.yaml
  tekton/ci/github-eventlistener.yaml
  tekton/ci/jobs.yaml
  tekton/ci/kustomization.yaml
  tekton/ci/plumbing-template.yaml
  tekton/ci/resources.yaml
  tekton/ci/tasks.yaml
  tekton/ci/tekton-golang-lint.yaml
  tekton/ci/tekton-image-build.yaml
  tekton/ci/tekton-noop-check.yaml
  tekton/ci/tekton-yamllint.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/serviceaccount.yaml
  tekton/resources/ci/bindings.yaml
  tekton/resources/ci/github-template.yaml
  tekton/resources/ci/kustomization.yaml
  tekton/resources/kustomization.yaml
Labels: approved, kind/cleanup, lgtm, size/L

#472 add prow job that enables cluster task auth webhook integration tests
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/M

#479 prow: env vars values needs to be strings 😅
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/XS

#481 Record having given build cop access to @sthaha
  buildbot/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#480 test-runner: do not use -u on go get…
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/misc, lgtm, size/S

#485 Don't use go modules for licenseclassifier.
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/bug, lgtm, size/XS

#487 Also disable go modules for go-licenses.
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/bug, lgtm, size/XS

#486 buildbot: use `ko://` scheme in deployment
  buildbot/config/deployment.yaml
Labels: approved, kind/misc, lgtm, size/XS

#489 Add an e2e test to the prow config for chains.
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/M

#493 Bump tkn version
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#490 labels: add a `kind/tep` label
  label_sync/labels.yaml
Labels: approved, kind/misc, lgtm, size/XS

#494 Update trigger template params to use tt.params
  tekton/ci/checks/check-pr-has-kind-label.yaml
  tekton/ci/plumbing-template.yaml
  tekton/mario-bot/mario-github-comment.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/cd/cleanup-template.yaml
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/folder-template.yaml
  tekton/resources/cd/helm-template.yaml
  tekton/resources/cd/notification-template.yaml
  tekton/resources/cd/tekton-template.yaml
  tekton/resources/ci/github-template.yaml
  tekton/resources/images/image-build-trigger.yaml
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
  tekton/resources/release/nightly-release-logs-trigger.yaml
Labels: approved, kind/misc, lgtm, size/L
