Repository tektoncd/plumbing, pull requests merged in 2020-03, with the labels that each got.

#257 Fix the label sync job
  prow/rbac.yaml
  tekton/cronjobs/labels-sync-cron/cronjob.yaml
  tekton/resources/cd/clusters.yaml
  tekton/resources/cd/label-sync-cd.yaml
Labels: approved, lgtm, size/M

#259 Regenerate rotation starting march 9th
  buildbot/rotation.csv
Labels: approved, lgtm, size/L

#258 Add area's roadmap and epic labels 🏷
  label_sync/labels.yaml
Labels: approved, lgtm, size/S

#261 Add a needs-cherry-pick label 🏷
  label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#263 Fix the configmap key for label_sync job 🕹
  tekton/resources/cd/label-sync-cd.yaml
Labels: approved, lgtm, size/XS

#264 Add support to rotation generator for swaps and holidays
  buildbot/cmd/generate-rotation-csv/README.md
  buildbot/cmd/generate-rotation-csv/main.go
  buildbot/cmd/generate-rotation-csv/main_test.go
  buildbot/rotation-overrides.csv
Labels: approved, lgtm, size/L

#267 fix typo
  gcp.md
Labels: approved, lgtm, ok-to-test, size/XS

#273 Adding a triage/wg-discuss 😅
  label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#274 Disable shrug ¯\\\_(ツ)_/¯
  label_sync/labels.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#279 Bump versions
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS

#275 Deploy latest triggers to robocat
  tekton/cd/triggers/overlays/robocat/kustomization.yaml
  tekton/cronjobs/robocat-triggers-deploy-latest-cron/README.md
  tekton/cronjobs/robocat-triggers-deploy-latest-cron/cronjob.yaml
  tekton/cronjobs/robocat-triggers-deploy-latest-cron/kustomization.yaml
Labels: approved, dependent, lgtm, size/M

#287 Prerelease Check: Only fail if version tag endings are exact match
  tekton/resources/release/prerelease_checks.yaml
Labels: approved, lgtm, size/XS
