Repository tektoncd/plumbing, pull requests merged in 2020-05, with the labels that each got.

#367 test-runner: remove useless rm -rf GOROOT 🐇
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS

#368 Ignore kind/misc in the list of uncategorised PRs
  tekton/resources/release/github_release.yaml
Labels: approved, lgtm, size/XS

#371 Pin verison of ko we install 📌
  tekton/images/ko-gcloud/Dockerfile
Labels: approved, lgtm, size/XS

#374 Fix the URL to the release in the oneliner install
  tekton/resources/release/github_release.yaml
Labels: approved, lgtm, size/XS

#375 Change ko:gcloud-latest image to ko-gcloud:latest
  tekton/cronjobs/ko-gcloud-image-nightly-build-cron/cronjob.yaml
  tekton/resources/release/install_tekton_release.yaml
Labels: approved, lgtm, size/XS

#377 Add --no-push to image builds 📃
  tekton/ci/jobs.yaml
Labels: approved, lgtm, size/XS

#376 Bump golangci-lint to 1.26.0
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS

#229 Add a check that a PR has a kind label
  tekton/ci/checks/check-pr-has-kind-label.yaml
Labels: approved, lgtm, ok-to-test, size/L

#381 Add the "kind label" check into the CI event listener
  tekton/ci/0001_rbac.yaml
  tekton/ci/checks/check-pr-has-kind-label.yaml
  tekton/ci/eventlistener.yaml
  tekton/ci/jobs.yaml
  tekton/cronjobs/labels-sync-dogfooding-cron/README.md
  tekton/cronjobs/labels-sync-dogfooding-cron/cronjob.yaml
  tekton/cronjobs/labels-sync-dogfooding-cron/kustomization.yaml
  tekton/resources/cd/clusters.yaml
Labels: approved, kind/feature, lgtm, size/L

#383 Add docs on robocat cluster location and make easier to find 🔎
  README.md
  addpermissions.py
  boskos/README.md
  buildbot/README.md
  gcp.md
  prow/README.md
  robocat/README.md
Labels: approved, kind/documentation, lgtm, size/M

#384 Add docs on secrets in the clusters 🤫
  README.md
  mariobot/README.md
  prow/README.md
  tekton/README.md
Labels: approved, kind/documentation, lgtm, size/L

#385 Add support for multi-repo on the ci webhook
  tekton/ci/checks/check-pr-has-kind-label.yaml
  tekton/ci/eventlistener.yaml
  tekton/ci/plumbing-template.yaml
Labels: approved, area/plumbing, kind/misc, lgtm, size/S

#388 Fix a small link typo, add the word "webhook" and ci-webhook entry
  README.md
Labels: approved, kind/documentation, lgtm

#389 Add the most important prow credential! 🤫
  README.md
  prow/README.md
Labels: approved, kind/documentation, lgtm, size/M

#390 Run the label check on PR sync
  tekton/ci/eventlistener.yaml
Labels: approved, kind/feature, lgtm, size/XS

#394 Add labels to the namespace to match the latest release
  robocat/cadmin/100-namespace.yaml
Labels: approved, kind/misc, lgtm, size/XS

#393 test-runner: remove githubhelper binary
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/cleanup, lgtm, size/XS

#396 buildbot: May 25th PTO vdemeest
  buildbot/rotation-overrides.csv
Labels: approved, kind/misc, lgtm, size/XS
