Repository tektoncd/plumbing, pull requests merged in 2020-10, with the labels that each got.

#597 Update tkn to v0.13.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#599 Improve the waiting in the tekton in kind script
  hack/tekton_in_kind.sh
Labels: approved, kind/feature, lgtm, size/XS

#594 prow: add nightly integration tests for catalog
  prow/config.yaml
Labels: approved, kind/feature, lgtm, size/S

#605 prow: fix catalog periodics
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/XS

#606 Fix the notification template
  tekton/resources/cd/notification-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#607 Add hacktoberfest-accepted label
  label_sync/labels.yaml
Labels: approved, kind/misc, lgtm, size/XS

#609 Handle the cases of many or no release notes
  tekton/resources/release/github_release.yaml
Labels: approved, kind/bug, lgtm, size/XS

#600 Bump ko version to v0.6.0
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS

#613 Remove myself from the build cop rotation 🧘❤️
  bots/buildbot/README.md
  bots/buildbot/rotation-overrides.csv
  bots/buildbot/rotation.csv
Labels: approved, kind/misc, lgtm, size/L

#610 Catlin: Fixes warning for images having tag along with digest
  catlin/pkg/validator/task_validator.go
  catlin/pkg/validator/task_validator_test.go
  catlin/pkg/validator/validate_test.go
Labels: approved, kind/bug, lgtm, size/S

#617 Update tkn to 0.13.1
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#618 Update google/go-licenses dependency
  go.mod
  go.sum
Labels: approved, kind/misc, lgtm, size/S

#619 Give Priti access to Tekton infra 🔑
  bots/buildbot/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#616 Add conformance tests to presubmit-tests.sh
  scripts/README.md
  scripts/presubmit-tests.sh
Labels: approved, kind/feature, lgtm, size/M

#623 fixing the link
  bots/buildbot/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#527 Added Multiarch support to gcr.io/tekton-releases/dogfooding/tkn:late…
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS
