Repository tektoncd/plumbing, pull requests merged in 2020-06, with the labels that each got.

#406 tektoncd/hub: enable prow job
  prow/config.yaml
Labels: approved, kind/feature, lgtm, size/L

#401 Add golang lint CI Job
  tekton/ci/jobs.yaml
  tekton/ci/plumbing-template.yaml
  tekton/ci/tekton-golang-lint.yaml
Labels: approved, kind/feature, lgtm, size/L

#408 Add a Dockerfile that adds a non-root user to alpine/git base
  tekton/ci/plumbing-template.yaml
  tekton/cronjobs/alpine-git-nonroot-image-nightly-build-cron/README.md
  tekton/cronjobs/alpine-git-nonroot-image-nightly-build-cron/cronjob.yaml
  tekton/cronjobs/alpine-git-nonroot-image-nightly-build-cron/kustomization.yaml
  tekton/images/alpine-git-nonroot/Dockerfile
Labels: approved, kind/misc, lgtm, size/M

#409 Fixes to draft release docs 📝
  tekton/resources/release/README.md
Labels: approved, kind/documentation, lgtm, size/M

#410 Add invalid-owners-file to missingLabels
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/XS

#412 Use lowercase project name in installation one-liner 🎣
  tekton/resources/release/github_release.yaml
Labels: approved, kind/bug, lgtm, size/XS

#369 Add an initial roadmap for plumbing
  roadmap.md
Labels: approved, area/roadmap, kind/documentation, lgtm, size/M

#414 Stagger nightly builds and their deploy to robocat
  tekton/cronjobs/dashboard-nightly-release-cron/cronjob.yaml
  tekton/cronjobs/robocat-dashboard-deploy-latest-cron/cronjob.yaml
  tekton/cronjobs/robocat-triggers-deploy-latest-cron/cronjob.yaml
  tekton/cronjobs/triggers-nightly-release-cron/cronjob.yaml
Labels: approved, kind/misc, lgtm, size/XS

#418 Add an area/performance label
  label_sync/labels.yaml
Labels: approved, kind/misc, lgtm, size/XS

#415 Set correct git and hub versions
  tekton/images/hub/Dockerfile
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#423 Fix golang-ci lint errors.
  dummy.go
  scripts/dummy.go
  tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go
Labels: approved, kind/cleanup, lgtm, size/M

#419 Add needs-rebase external plugins…
  prow/plugins.yaml
Labels: approved, kind/misc, lgtm, size/XS

#421 Document usage of workload-id node pool in dogfooding
  README.md
Labels: approved, kind/documentation, lgtm, size/S

#422 Add config for Tekton chains presubmits.
  prow/config.yaml
Labels: approved, kind/feature, lgtm, size/M

#425 Add Jerop to build cop rotation 🚨
  addpermissions.py
  buildbot/README.md
  buildbot/rotation-overrides.csv
  buildbot/rotation.csv
Labels: approved, kind/misc, lgtm, size/L

#428 Adjust week with fourth of july holidays 🎇
  buildbot/rotation-overrides.csv
  buildbot/rotation.csv
Labels: approved, kind/misc, lgtm, size/S

#429 Add cover for july 17th
  buildbot/rotation-overrides.csv
  buildbot/rotation.csv
Labels: approved, kind/misc, lgtm, size/L

#430 Update golangci
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#431 Upgrade tkn to v0.10.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#433 Change the kustomise setup to use bindings ref
  tekton/resources/nightly-release/base/eventlistener.yaml
  tekton/resources/nightly-release/base/kustomizeconfig/eventlistener.yaml
Labels: approved, kind/bug, lgtm, size/XS

#434 Update golangci-lint CI Job Version to 1.27.0
  tekton/ci/jobs.yaml
Labels: approved, kind/feature, lgtm, size/XS

#437 Use binding ref in mario bot
  tekton/resources/mario-bot/mario-github-comment.yaml
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
Labels: approved, kind/bug, lgtm, size/XS

#438 prow: disable go-coverage jobs on tektoncd/hub
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/M

#436 Pin the version of gloud that we use
  tekton/images/ko-gcloud/Dockerfile
Labels: approved, kind/cleanup, lgtm, size/S

#420 Restore compatibility with triggers v0.5.0
  mariobot/README.md
  tekton/ci/eventlistener.yaml
  tekton/ci/github-eventlistener.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/images/image-build-trigger.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
  tekton/resources/release/nightly-release-logs-trigger.yaml
Labels: approved, kind/bug, lgtm, size/M

#443 Update Dashboard Robocat deployment cronjob to match pipeline and triggers
  tekton/cronjobs/robocat-dashboard-deploy-latest-cron/cronjob.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#442 Automatically delete old pr and tr on dogfooding
  tekton/cronjobs/cleanup-cd-cron-base/README.md
  tekton/cronjobs/cleanup-cd-cron-base/kustomization.yaml
  tekton/cronjobs/cleanup-cd-cron-base/trigger-resource-cd.yaml
  tekton/cronjobs/dogfooding-cleanup-default-cron/README.md
  tekton/cronjobs/dogfooding-cleanup-default-cron/cronjob.yaml
  tekton/cronjobs/dogfooding-cleanup-default-cron/kustomization.yaml
  tekton/cronjobs/dogfooding-cleanup-tektonci-cron/README.md
  tekton/cronjobs/dogfooding-cleanup-tektonci-cron/cronjob.yaml
  tekton/cronjobs/dogfooding-cleanup-tektonci-cron/kustomization.yaml
  tekton/resources/cd/bindings.yaml
  tekton/resources/cd/cleanup-template.yaml
  tekton/resources/cd/clusters.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/serviceaccount.yaml
  tekton/resources/kustomization.yaml
Labels: approved, kind/feature, lgtm, size/L

#417 Create a script to deploy tekton releases
  scripts/README.md
  scripts/deploy-release.sh
Labels: approved, area/dogfooding, kind/feature, lgtm, size/L

#445 Simplify cleanup task
  tekton/resources/cd/cleanup-template.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#424 Enable release-note and few other plugins 👼
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, kind/misc, lgtm, size/S

#440 Add kind/question back to the labels 🏷
  label_sync/labels.yaml
Labels: approved, kind/misc, lgtm, size/XS

#441 Add releasnote* labels back 🏷
  label_sync/labels.yaml
Labels: approved, kind/misc, lgtm, size/S
