Repository tektoncd/plumbing, pull requests merged in 2020-01, with the labels that each got.

#177 Add dogfooding cluster to docs
  gcp.md
Labels: approved, lgtm, size/XS

#184 Swap rotation on Jan 23
  buildbot/rotation.csv
Labels: approved, lgtm, size/XS

#188 Update the boskos image
  boskos/boskos.yaml
Labels: approved, area/boskos, lgtm, size/XS

#189 Fix "install-tekton-release"
  tekton/cd/README.md
  tekton/resources/release/install_tekton_release.yaml
Labels: approved, lgtm, size/S

#190 Fix kustomize layers
  tekton/resources/images/image-build-trigger.yaml
  tekton/resources/kustomization.yaml
  tekton/resources/mario-bot/mario-github-comment.yaml
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/nightly-release/base/kustomization.yaml
Labels: approved, lgtm, size/XS

#191 Fix the eventlistener kustomize config
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/nightly-release/base/kustomizeconfig/eventlistener.yaml
  tekton/resources/nightly-release/base/serviceaccount.yaml
Labels: approved, lgtm, size/M

#192 Fix the trigger template for nightly releases
  tekton/resources/nightly-release/base/template.yaml
Labels: approved, lgtm, size/XS

#194 Use the latest boskos ✨
  boskos/boskos.yaml
Labels: approved, lgtm, size/XS

#195 Allow project to specify a yamllint config
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#175 Add release.notags.yaml file to the release page 💫
  tekton/resources/release/github_release.yaml
Labels: approved, lgtm, size/XS

#198 Adapt Mario to triggers v0.2.1 and pipelines v0.10.0
  cmd/mario/kodata/LICENSE
  cmd/mario/kodata/OWNERS
  mariobot/README.md
  mariobot/cmd/mario/kodata/LICENSE
  mariobot/cmd/mario/kodata/OWNERS
  mariobot/cmd/mario/main.go
  mariobot/config/100-namespace.yaml
  mariobot/config/200-serviceaccount.yaml
  mariobot/config/mario.yaml
  tekton/resources/mario-bot/mario-github-comment.yaml
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
Labels: approved, lgtm, size/S

#199 Fix a typo
  mariobot/cmd/mario/main.go
Labels: approved, lgtm, size/XS

#200 Upgrade to Kustomize 3.5.4
  tekton/images/ko/Dockerfile
Labels: approved, lgtm, size/XS

#202 Prepend "mario" to mario-bot resources
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
Labels: approved, lgtm, size/XS

#204 Use kustomize 3.5.4 in the ko-gcloud image
  tekton/images/ko-gcloud/Dockerfile
Labels: approved, lgtm, size/XS
