Repository tektoncd/plumbing, pull requests merged in 2020-08, with the labels that each got.

#498 Handle the issue of labels with quotes within description
  tekton/ci/checks/check-pr-has-kind-label.yaml
Labels: approved, kind/bug, lgtm, size/XS

#499 remove job related to https://github.com/tektoncd/pipeline/pull/2797
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/M

#500 Add nop-image resource to pipline trigger template
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: approved, kind/misc, lgtm, size/XS

#501 peribolos: update/fix teams too
  tekton/resources/org-permissions/peribolos.yaml
Labels: approved, kind/misc, lgtm, size/XS

#506 Extend /test to more repos in tektoncd
  tekton/ci/eventlistener.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#503 Run the GitHub check update task as non-root
  tekton/resources/ci/github-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#508 Update params to tt.params in missed files
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: approved, kind/misc, lgtm, size/S

#497 Automate Issues and Pull Requests Lifecycle
  prow/config.yaml
Labels: approved, kind/feature, lgtm, size/L

#510 Fix the golang lint check name
  tekton/ci/plumbing-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#507 Deploy Tekton resources hourly to dogfooding
  tekton/cronjobs/dogfooding/manifests/kustomization.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs/README.md
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs/kustomization.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton/README.md
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#511 Use tt.params in resourceSpec
  tekton/ci/plumbing-template.yaml
Labels: approved, kind/bug, lgtm, size/S

#512 Remove the noop job
  tekton/ci/plumbing-template.yaml
  tekton/ci/tekton-noop-check.yaml
Labels: approved, kind/cleanup, lgtm, size/L

#514 Stop creating pipeline resources in trigger templates
  tekton/ci/kustomization.yaml
  tekton/mario-bot/mario-github-comment.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/folder-template.yaml
  tekton/resources/ci/github-template.yaml
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
Labels: approved, kind/cleanup, lgtm, size/L

#521 Increase the number of replicas for tekton-events
  tekton/resources/cd/eventlistener.yaml
Labels: approved, kind/misc, lgtm, size/XS

#520 prow: fix query for stale, rotten and close issues
  prow/config.yaml
Labels: approved, kind/bug, lgtm, size/XS

#519 Use embedded storage resources for nightly releases
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: approved, kind/bug, lgtm, size/L

#522 Add git url to templates for nightlies
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#523 Fix json patch path for templates
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#525 Fixup apiVersion appearing in resourceTemplates
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#528 Update TriggerTemplate overlays to use different path
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#524 Update old folder name
  tekton/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#531 Stop using log app in CI links and improve dashboard link
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/ci/bindings.yaml
  tekton/resources/ci/github-template.yaml
Labels: approved, kind/cleanup, lgtm, size/M

#515 Update dashboard integration test job
  prow/config.yaml
Labels: approved, kind/cleanup, lgtm, size/M

#399 Remove helm related jobs
  prow/config.yaml
Labels: approved, kind/cleanup, lgtm, size/M

#533 Use tt.params in the github update tasks
  tekton/resources/ci/github-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#532 Reduce the chance of race condition on github update
  tekton/resources/ci/github-template.yaml
Labels: approved, kind/bug, lgtm, size/S

#529 Add a custom interceptor for team members
  tekton/ci/bindings.yaml
  tekton/ci/eventlistener.yaml
  tekton/ci/interceptors/add-team-members/README.md
  tekton/ci/interceptors/add-team-members/cmd/add-team-members/kodata/LICENSE
  tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go
  tekton/ci/interceptors/add-team-members/cmd/add-team-members/main_test.go
  tekton/ci/interceptors/add-team-members/config/100-namespace.yaml
  tekton/ci/interceptors/add-team-members/config/200-serviceaccount.yaml
  tekton/ci/interceptors/add-team-members/config/add-team-members.yaml
  tekton/ci/kustomization.yaml
  tekton/ci/tekton-cd-template.yaml
Labels: approved, kind/feature, lgtm, size/XL

#454 prow: using presets to remove duplicates in jobs…
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/XL

#535 Update boskos images to latest
  boskos/boskos.yaml
Labels: approved, kind/bug, lgtm, size/XS

#536 Fix github check status while pending
  tekton/resources/ci/github-template.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#543 prow: fix tektoncd/cli coverage typo
  prow/config.yaml
Labels: approved, kind/bug, lgtm, size/XS

#544 OWNERS: update based on buildcops 🙃
  OWNERS
Labels: approved, kind/misc, lgtm, size/XS

#545 yamllint: temporary disable buildbot and mariobot
  tekton/ci/plumbing-template.yaml
Labels: approved, kind/misc, lgtm, size/XS

#549 Update rotation.csv path for the rotationURL
  bots/buildbot/cmd/buildbot/main.go
Labels: approved, kind/misc, lgtm, size/XS

#551 Update tkn to v0.12.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#547 Correct the pipeline version for PROW integration.
  docs/prow.md
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS
