Repository tektoncd/plumbing, pull requests merged in 2020-11, with the labels that each got.

#625 Add buildx-gcloud image to plumbing
  tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/README.md
  tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/kustomization.yaml
  tekton/images/buildx-gcloud/Dockerfile
Labels: approved, kind/misc, lgtm, size/M

#620 add CI/CD pipeline for the tekton website
  tekton/ci/eventlistener.yaml
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/jobs/tekton-python-test.yaml
  tekton/ci/templates/kustomization.yaml
  tekton/ci/templates/website-template.yaml
Labels: approved, area/testing, kind/feature, lgtm, size/L

#622 fix issues when setup tekton with kind
  DEVELOPMENT.md
  hack/tekton_in_kind.sh
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS

#630 Fix the name of the tekton website trigger template
  tekton/ci/templates/website-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#627 Add the buildx cronjob to kustomize so it gets deployed
  tekton/cronjobs/README.md
  tekton/cronjobs/dogfooding/images/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/S

#633 prow: use our own coverage image
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/S

#629 Add build of dogfooding images in multi-arch form
  tekton/cronjobs/bases/image-build/trigger-image-build.yaml
  tekton/cronjobs/dogfooding/images/alpine-git-nonroot-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/skopeo-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/tkn-nightly/cronjob.yaml
  tekton/resources/images/bindings.yaml
  tekton/resources/images/eventlistener.yaml
  tekton/resources/images/kustomization.yaml
  tekton/resources/images/multi-arch-template.yaml
  tekton/resources/images/single-arch-template.yaml
  tekton/resources/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/L

#635 Update the version of peribolos
  tekton/resources/org-permissions/peribolos.yaml
Labels: approved, kind/misc, lgtm, size/XS

#634 Dockerfiles: bump golang to 1.15 ⚓
  catlin/Dockerfile
  pipelinerun-logs/Dockerfile
  scripts/library.sh
  tekton/images/coverage/Dockerfile
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/kubectl/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/misc, lgtm, size/M

#637 Add bef args as valid to deploy-release script
  scripts/deploy-release.sh
Labels: approved, kind/misc, lgtm, size/XS

#638 prow: Fix catalog periodic jobs
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/XS

#640 Add a teps image
  tekton/cronjobs/dogfooding/images/kustomization.yaml
  tekton/cronjobs/dogfooding/images/teps-community-nightly/README.md
  tekton/cronjobs/dogfooding/images/teps-community-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/teps-community-nightly/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/M

#642 scripts: Fix list_changed_files in presubmit-tests
  scripts/presubmit-tests.sh
Labels: approved, kind/bug, lgtm, size/XS

#632 New script to deploy Tekton CI into local kind cluster
  DEVELOPMENT.md
  hack/tekton_ci.sh
Labels: approved, kind/misc, lgtm, ok-to-test, size/L

#644 prow: Fix catalog periodic job
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/XS

#643 Update tkn to 0.14.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#641 Add a teps CI job for the community repo
  tekton/ci/eventlistener.yaml
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/jobs/tekton-teps-validation.yaml
  tekton/ci/templates/community-template.yaml
  tekton/ci/templates/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/L

#647 scripts: Make sure `cat` params are quoted.
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
Labels: approved, kind/misc, lgtm, size/S

#648 Remove Dashboard postsubmit job
  prow/config.yaml
Labels: approved, kind/cleanup, lgtm, size/S

#650 Fix the plumbing URL in the kubectl nightly
  tekton/cronjobs/dogfooding/images/kubectl-nightly/cronjob.yaml
Labels: approved, kind/bug, lgtm, size/XS

#646 Add kind to test-runner image.
  tekton/images/test-runner/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#645 Add information to documentation how to build multi-arch dogfooding image
  tekton/cronjobs/README.md
Labels: approved, kind/documentation, lgtm, size/S

#651 Add instructions for frozen lifecycle and request justifications
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/S
