Repository tektoncd/plumbing, pull requests merged in 2020-04, with the labels that each got.

#289 Add pull-tekton-experimental-helm-lint
  prow/config.yaml
Labels: approved, lgtm, ok-to-test, size/M

#294 Add tektoncd/hub to tide 👼
  prow/config.yaml
Labels: approved, lgtm, size/XS

#297 Update the version of hub to satify constrainst
  tekton/images/hub/Dockerfile
Labels: approved, lgtm, size/XS

#285 Migrate pipeline resources to v1beta1
  tekton/ci/github-template.yaml
  tekton/ci/jobs.yaml
  tekton/ci/plumbing-template.yaml
  tekton/ci/tasks.yaml
  tekton/ci/tekton-noop-check.yaml
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/folder-template.yaml
  tekton/resources/cd/helm-template.yaml
  tekton/resources/cd/tekton-template.yaml
  tekton/resources/images/image-build-trigger.yaml
  tekton/resources/mario-bot/mario-github-comment.yaml
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
  tekton/resources/org-permissions/peribolos-run.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
  tekton/resources/org-permissions/peribolos.yaml
  tekton/resources/release/github_release.yaml
  tekton/resources/release/install_and_test_tekton_release.yaml
  tekton/resources/release/install_tekton_release.yaml
  tekton/resources/release/nightly-release-logs-trigger.yaml
  tekton/resources/release/prerelease_checks.yaml
  tekton/resources/release/save-release-logs.yaml
  tekton/resources/release/test_tekton_release.yaml
Labels: approved, dependent, lgtm, size/XXL

#296 Improve tekton-experimental-helm-lint prow job
  prow/config.yaml
Labels: approved, lgtm, ok-to-test, size/M

#298 Migrate all triggers resources to triggers.tekton.dev
  tekton/ci/0001_rbac.yaml
  tekton/ci/bindings.yaml
  tekton/ci/eventlistener.yaml
  tekton/ci/github-eventlistener.yaml
  tekton/ci/github-template.yaml
  tekton/ci/plumbing-template.yaml
  tekton/resources/cd/bindings.yaml
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/folder-template.yaml
  tekton/resources/cd/helm-template.yaml
  tekton/resources/cd/serviceaccount.yaml
  tekton/resources/cd/tekton-template.yaml
  tekton/resources/images/image-build-trigger.yaml
  tekton/resources/mario-bot/mario-github-comment.yaml
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/nightly-release/base/bindings.yaml
  tekton/resources/nightly-release/base/eventlistener.yaml
  tekton/resources/nightly-release/base/serviceaccount.yaml
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/nightly-release/overlays/dashboard/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline/kustomization.yaml
  tekton/resources/nightly-release/overlays/triggers/kustomization.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
  tekton/resources/release/nightly-release-logs-trigger.yaml
Labels: approved, lgtm, size/L

#290 Add python3 to the image 😛
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS

#299 Add sbwsg to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#300 Update OWNER policy 👩‍⚖️
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#301 Fix the JSON payload for configmap deploy jobs
  tekton/cronjobs/configmap-cd-cron-base/trigger-resource-cd.yaml
Labels: approved, lgtm, size/XS

#295 test-runner: self-contained dockerfile
  tekton/images/test-runner/Dockerfile
  tekton/images/test-runner/entrypoint.sh
  tekton/images/test-runner/runner.sh
Labels: approved, lgtm, size/L

#303 One v1beta1 fixed slipped through
  tekton/resources/release/install_tekton_release.yaml
Labels: approved, lgtm, size/XS

#302 Add decorate flag on pull-tekton-experimental-helm-lint
  prow/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#304 Add the resource and docs to drive dogfooding from robocat
  robocat/README.md
  tekton/resources/cd/clusters.yaml
Labels: approved, lgtm, size/M

#305 Fix pull-tekton-experimental-helm-lint
  prow/config.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#308 Add a label for automation issues in the website repo
  label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#311 Add ingress and fix role for Mario
  tekton/resources/mario-bot/ingress.yaml
  tekton/resources/mario-bot/mario-image-build-trigger.yaml
Labels: approved, lgtm, size/S

#312 Update Mario's CEL filter for v1beta1
  tekton/resources/mario-bot/mario-github-comment.yaml
Labels: approved, lgtm, size/XS

#310 Fix test-runner image: use python2 for bootstrap
  tekton/images/test-runner/Dockerfile
  tekton/images/test-runner/entrypoint.sh
Labels: approved, lgtm, size/XS

#313 Use test-runner:safe temporarly 😅
  prow/config.yaml
Labels: approved, lgtm, size/M

#314 Create a temporary job on plumbing 😏
  prow/config.yaml
Labels: approved, lgtm, size/M

#316 test-runner: update pull-dogfooding-mario-test
  prow/config.yaml
  tekton/images/test-runner/test.sh
Labels: approved, lgtm, size/XS

#317 Update tkn Image to v0.8.0
  tekton/images/tkn/Dockerfile
Labels: approved, lgtm, size/XS

#318 Remove buildbot Dockerfile 🤖
  buildbot/Dockerfile
Labels: approved, lgtm, size/XS

#320 prow: add a 0.10.x prow job for tektoncd/cli
  prow/config.yaml
Labels: approved, lgtm, size/M

#322 prow: fix cli-integratino-test-0_10
  prow/config.yaml
Labels: approved, lgtm, size/XS

#323 Fix pull-tekton-cli-integration-tests-0_10 😓
  prow/config.yaml
Labels: approved, lgtm, size/XS

#321 Add missing charts to be linted
  prow/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#327 Fix postsubmit logs location
  prow/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#325 Remove tekton-pipeline-publish-images 🐶
  prow/config.yaml
Labels: approved, lgtm, size/M

#329 Switch to latest tag for post coverage jobs
  prow/config.yaml
Labels: approved, lgtm, size/XS

#324 Add prow job to check helm doc is up to date
  prow/config.yaml
Labels: approved, lgtm, ok-to-test, size/S

#332 Add more missingLabels 🏷
  prow/config.yaml
Labels: approved, lgtm, size/XS

#331 Add do-not-merge/requires-pipelines-0.12 knowledge…
  label_sync/labels.yaml
  prow/config.yaml
Labels: approved, lgtm, size/XS

#315 test-runner image spring cleaning
  tekton/images/test-runner/Dockerfile
  tekton/images/test-runner/entrypoint.sh
  tekton/images/test-runner/runner.sh
  tekton/images/test-runner/test.sh
Labels: approved, lgtm, size/L

#338 Disable the try-out-prow-plus-tekton job
  prow/config.yaml
Labels: approved, lgtm, size/XS

#340 Fix non existing image gcr.io/knative-tests/test-infra/coverage:safe
  prow/config.yaml
Labels: approved, lgtm, size/XS

#341 More cleanups on test-runner 🗜
  tekton/images/test-runner/Dockerfile
  tekton/images/test-runner/runner.sh
Labels: approved, lgtm, size/M

#343 Only run demo jobs for demos
  tekton/ci/plumbing-template.yaml
Labels: approved, lgtm, size/XS

#345 Add roles and rolebindings tekton-deployer
  robocat/cadmin/200-rbac.yaml
Labels: approved, lgtm, size/XS

#339 Add prow job to check chart version increment
  prow/config.yaml
Labels: approved, lgtm, size/S

#346 Use :latest instead of :safe for experimental 😑
  prow/config.yaml
Labels: approved, lgtm, size/XS

#347 Specficy commands for decorated jobs 🗡
  prow/config.yaml
Labels: approved, lgtm, size/XS

#349 Clone licenseclassifier in GOPATH to fix go-licenses
  tekton/images/test-runner/entrypoint.sh
Labels: approved, lgtm, size/XS

#351 Add kustomize 3.5.4 to test-runner 🛴
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS

#330 Add a job for building PR images 🐉
  tekton/ci/jobs.yaml
  tekton/ci/plumbing-template.yaml
  tekton/ci/tekton-image-build.yaml
Labels: approved, lgtm, size/L

#354 Fix the Tekton CI job to build and push images
  tekton/ci/jobs.yaml
  tekton/ci/tekton-image-build.yaml
Labels: approved, lgtm, size/S

#350 Use go-licenses for all licenses cases 👼
  scripts/library.sh
Labels: approved, lgtm, size/S

#352 Safe back to latest
  prow/config.yaml
Labels: approved, lgtm, size/L

#356 Remove running go test during build 🚏
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#357 Simpler list_changed_files 🍶
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#358 Fix pull-tekton-operator-unit-tests prow job 🕹
  prow/config.yaml
Labels: approved, lgtm, size/XS

#359 Bump coverage image to latest
  prow/config.yaml
Labels: approved, lgtm, size/XS

#360 Make threshold zero
  prow/config.yaml
Labels: approved, lgtm, size/XS

#363 Import coverage image from knative/test-infra 🍨
  tekton/ci/plumbing-template.yaml
  tekton/cronjobs/coverage-image-nightly-build-cron/README.md
  tekton/cronjobs/coverage-image-nightly-build-cron/cronjob.yaml
  tekton/cronjobs/coverage-image-nightly-build-cron/kustomization.yaml
  tekton/images/coverage/Dockerfile
Labels: approved, lgtm, size/L

#364 Upgrade tkn to v0.9.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, lgtm, size/XS

#365 Fix kaniko-build-push tektonci job 🕹
  tekton/ci/jobs.yaml
  tekton/ci/tekton-image-build.yaml
Labels: approved, lgtm, size/S

#362 Use knative.dev in clone in test-runner 🛴
  tekton/images/test-runner/Dockerfile
Labels: approved, lgtm, size/XS

#366 Improve the release automation task
  label_sync/labels.yaml
  tekton/resources/release/github_release.yaml
Labels: approved, lgtm, size/L
