Repository tektoncd/plumbing, pull requests merged in 2021-08, with the labels that each got.

#866 Add SYSTEM_NAMESPACE env variable to fix cli tests for Z and Power
  tekton/resources/nightly-tests/bastion-p/test_tekton_cli.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_cli.yaml
Labels: approved, kind/misc, lgtm, size/XS

#792 Add task for nightly release installation, common for all architectures
  tekton/resources/nightly-tests/README.md
  tekton/resources/nightly-tests/base/deploy_tekton_component.yaml
  tekton/resources/nightly-tests/base/kustomization.yaml
  tekton/resources/nightly-tests/bastion-z/deploy_tekton_pipeline.yaml
  tekton/resources/nightly-tests/bastion-z/deploy_tekton_triggers.yaml
  tekton/resources/nightly-tests/bastion-z/kustomization.yaml
  tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Labels: lgtm, approved, size/L, kind/misc

#870 Make the description more clear
  hack/README.md
Labels: lgtm, approved, size/XS, kind/documentation, ok-to-test

#873 Remove "hello scott" prow experiment ⛵
  docs/prow.md
  prow/config.yaml
  prow/helloscott.yaml
Labels: lgtm, approved, size/M, kind/cleanup

#874 Update kustomization for operator nightly
  tekton/resources/nightly-release/overlays/operator/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#872 Add doc for signing releases with Tekton Chains
  docs/signing.md
Labels: lgtm, approved, size/M, kind/documentation

#871 Add combine script, to combine two manifest lists and push the result
  cmd/combine/README.md
  cmd/combine/main.go
  go.mod
  go.sum
Labels: kind/feature, lgtm, approved, size/XXL

#748 Catlin: Adds check for `category` annotation
  catlin/.env
  catlin/go.mod
  catlin/go.sum
  catlin/pkg/cmd/validate/testdata/task/black/0.1/black.yaml
  catlin/pkg/cmd/validate/testdata/task/maven/0.1/maven.yaml
  catlin/pkg/cmd/validate/testdata/task/npm/0.1/npm.yaml
  catlin/pkg/cmd/validate/validate.go
  catlin/pkg/cmd/validate/validate_test.go
  catlin/pkg/consts/consts.go
  catlin/pkg/validator/content_validator.go
  catlin/pkg/validator/helper.go
  catlin/pkg/validator/validate_test.go
Labels: kind/feature, lgtm, approved, size/L

#876 Fix ko-gcloud build
  tekton/images/ko-gcloud/Dockerfile
Labels: kind/bug, lgtm, approved, size/XS

#875 Update yamllint to not use resources 🤩
  tekton/ci/README.md
  tekton/ci/jobs/conditions.yaml
  tekton/ci/jobs/tasks.yaml
  tekton/ci/jobs/tekton-yamllint.yaml
  tekton/ci/templates/plumbing-template.yaml
Labels: lgtm, approved, size/L, kind/cleanup

#881 Bump Results to v0.3.0, enable temp certs for cert-manager.
  tekton/cd/results/base/kustomization.yaml
  tekton/cd/results/overlays/dogfooding/ingress.yaml
Labels: lgtm, approved, size/XS, kind/misc
