Repository tektoncd/plumbing, pull requests merged in 2021-03, with the labels that each got.

#718 prow: Add dind and kind presets.
  prow/config.yaml
Labels: approved, kind/misc, lgtm, size/M

#745 Replace template name with ref
  tekton/ci-workspace/community/trigger.yaml
  tekton/ci-workspace/infra/0001_rbac.yaml
  tekton/ci-workspace/shared/eventlistener.yaml
  tekton/ci-workspace/shared/trigger.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
Labels: approved, kind/misc, lgtm, size/S

#744 Run task-loops nightly builds
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/task-loops-nightly/README.md
  tekton/cronjobs/dogfooding/releases/task-loops-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/task-loops-nightly/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/task-loops/kustomization.yaml
  tekton/resources/nightly-release/overlays/task-loops/template.yaml
  tekton/resources/nightly-release/overlays/task-loops/trigger.yaml
Labels: approved, kind/misc, lgtm, size/M

#746 Fix deployment of task-loops resources
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/task-loops/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#750 Update experimental reference to use main…
  tekton/resources/nightly-release/overlays/task-loops/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#751 Fix Catlin CI to skip validation if no task change
  tekton/ci/jobs/tekton-catlin-lint.yaml
Labels: approved, kind/bug, lgtm, size/XS

#752 Update dashboard reference to use main…
  tekton/resources/nightly-release/overlays/dashboard/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#747 Add nightly builds for pip and cel custom tasks
  tekton/cronjobs/dogfooding/releases/cel-nightly/README.md
  tekton/cronjobs/dogfooding/releases/cel-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/cel-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/pipelines-in-pipelines-nightly/README.md
  tekton/cronjobs/dogfooding/releases/pipelines-in-pipelines-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pipelines-in-pipelines-nightly/kustomization.yaml
  tekton/resources/nightly-release/overlays/cel/kustomization.yaml
  tekton/resources/nightly-release/overlays/cel/template.yaml
  tekton/resources/nightly-release/overlays/cel/trigger.yaml
  tekton/resources/nightly-release/overlays/pipelines-in-pipelines/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipelines-in-pipelines/template.yaml
  tekton/resources/nightly-release/overlays/pipelines-in-pipelines/trigger.yaml
Labels: approved, kind/misc, lgtm, size/L

#754 Add the two new cronjobs to kustomize
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#755 Fix size of workspace volume for s390x triggers pipeline
  tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#756 Add several cleanup cronjobs for new namespaces
  tekton/cronjobs/dogfooding/cleanup/bastion-z-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/cleanup/kustomization.yaml
  tekton/cronjobs/dogfooding/cleanup/tekton-nightly-nightly/cronjob.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#757 Use larger workspaces for s390x pipelines
  tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#753 Add pipeline to run s390x operator tests
  tekton/cronjobs/dogfooding/nightly-tests/s390x/kustomization.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/kustomization.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
  tekton/resources/nightly-tests/kustomization.yaml
  tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
Labels: approved, kind/misc, lgtm, size/L

#759 Handle mixed main repo names in triggers
  tekton/cronjobs/bases/release/trigger-with-uuid.yaml
Labels: approved, kind/misc, lgtm, size/XS

#749 Add nightly builds for the custom interceptors
  tekton/ci-workspace/infra/0001_rbac.yaml
  tekton/ci-workspace/jobs/tekton-teps-validation.yaml
  tekton/ci/interceptors/add-pr-body/go.mod
  tekton/ci/interceptors/add-pr-body/go.sum
  tekton/ci/interceptors/add-pr-body/tekton/README.md
  tekton/ci/interceptors/add-pr-body/tekton/kustomization.yaml
  tekton/ci/interceptors/add-pr-body/tekton/publish.yaml
  tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml
  tekton/ci/interceptors/add-team-members/go.mod
  tekton/ci/interceptors/add-team-members/go.sum
  tekton/ci/interceptors/add-team-members/tekton/README.md
  tekton/ci/interceptors/add-team-members/tekton/kustomization.yaml
  tekton/ci/interceptors/add-team-members/tekton/publish.yaml
  tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml
  tekton/cronjobs/dogfooding/releases/add-pr-body-nightly/README.md
  tekton/cronjobs/dogfooding/releases/add-pr-body-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/add-pr-body-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/add-team-members-nightly/README.md
  tekton/cronjobs/dogfooding/releases/add-team-members-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/add-team-members-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/template.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/trigger.yaml
  tekton/resources/nightly-release/overlays/add-team-members/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-team-members/template.yaml
  tekton/resources/nightly-release/overlays/add-team-members/trigger.yaml
Labels: approved, kind/feature, lgtm, size/XL

#743 Add unit tests CI for the plumbing repo
  tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/jobs/tasks.yaml
  tekton/ci/jobs/tekton-golang-tests.yaml
  tekton/ci/templates/plumbing-template.yaml
Labels: approved, kind/feature, lgtm, size/L

#763 Fix master to main for interceptor nightlies
  tekton/resources/nightly-release/overlays/add-pr-body/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-team-members/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#761 Add documentation about s390x tests setup
  tekton/cronjobs/dogfooding/nightly-tests/s390x/cli-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/s390x/pipeline-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/s390x/triggers-nightly-test/README.md
  tekton/resources/README.md
  tekton/resources/nightly-tests/README.md
Labels: approved, kind/documentation, lgtm, size/M

#765 Continue working on unit tests for plumbing repo
  tekton/ci-workspace/jobs/kustomization.yaml
  tekton/ci-workspace/jobs/tekton-golang-tests.yaml
  tekton/ci-workspace/jobs/tekton-teps-validation.yaml
  tekton/ci-workspace/kustomization.yaml
  tekton/ci-workspace/plumbing/kustomization.yaml
  tekton/ci-workspace/plumbing/template.yaml
  tekton/ci-workspace/plumbing/trigger.yaml
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/templates/plumbing-template.yaml
Labels: approved, kind/misc, lgtm, size/L

#766 Fix the koparse config for add-team-members
  tekton/ci/interceptors/add-team-members/tekton/publish.yaml
Labels: approved, kind/misc, lgtm, size/XS

#771 Stop using $(uid) for resource names in templates
  tekton/ci-workspace/community/template.yaml
  tekton/mario-bot/mario-github-comment.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
Labels: approved, kind/misc, lgtm, size/XS

#772 Fix the branch selection in cronjobs
  tekton/cronjobs/bases/release/trigger-with-uuid.yaml
Labels: approved, kind/misc, lgtm, size/XS

#769 Update cli reference to use main…
  prow/config.yaml
  tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml
Labels: approved, kind/misc, lgtm, size/XS

#775 Update release pipeline resource list for Operator nightly
  tekton/resources/nightly-release/overlays/operator/kustomization.yaml
  tekton/resources/nightly-release/overlays/operator/template.yaml
Labels: approved, kind/misc, lgtm, size/XS

#774 Update pipeline reference to use main… 🧙
  docs/prow.md
  prow/config.yaml
  tekton/resources/nightly-release/overlays/pipeline/kustomization.yaml
  tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Labels: approved, kind/misc, lgtm, size/S

#767 Add corresponding RoleBindings for cleanup pipelineruns
  tekton/cronjobs/README.md
  tekton/resources/cd/serviceaccount.yaml
Labels: approved, kind/bug, lgtm, size/M

#779 Fix Catlin to skip deleted tasks
  tekton/ci/jobs/tekton-catlin-lint.yaml
Labels: approved, kind/bug, lgtm, size/XS

#777 bump tkn to v0.17.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#781 Updated wording related to what runs on the prow cluster
  docs/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#780 Fix namespace specification with kustomize for cleanup RoleBindings
  tekton/resources/cd/kustomization.yaml
Labels: approved, kind/bug, lgtm, size/S

#783 Fix unsupported template.name
  tekton/resources/nightly-tests/eventlistener.yaml
Labels: approved, kind/bug, lgtm, size/XS

#784 Switch Event Listener sinks to ClusterIP
  bots/mariobot/README.md
  tekton/ci-workspace/shared/eventlistener.yaml
  tekton/ci/eventlistener.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
Labels: approved, kind/misc, lgtm, size/XS

#788 Fix duplicate DIND env var due to preset 🧙
  prow/config.yaml
Labels: approved, kind/misc, lgtm

#785 Change the last master reference to main 🧙
  prow/config.yaml
  tekton/resources/nightly-release/README.md
  tekton/resources/release/base/github_release.yaml
Labels: approved, kind/misc, lgtm, size/S

#787 Have separate installation task for triggers for s390x tests
  tekton/resources/nightly-tests/bastion-z/deploy_tekton_pipeline.yaml
  tekton/resources/nightly-tests/bastion-z/deploy_tekton_triggers.yaml
  tekton/resources/nightly-tests/bastion-z/kustomization.yaml
  tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Labels: approved, kind/misc, lgtm, size/M

#758 Catlin: Report logs back to the PR after execution
  tekton/ci/jobs/tekton-catlin-lint.yaml
  tekton/ci/templates/catalog-template.yaml
Labels: approved, kind/feature, lgtm, size/M

#793 Move s390x pipeline test cronjob to another time
  tekton/cronjobs/dogfooding/nightly-tests/s390x/pipeline-nightly-test/cronjob.yaml
Labels: approved, kind/misc, lgtm, size/XS

#773 Use a TaskLoop to run container image builds in CI
  tekton/ci-workspace/jobs/kustomization.yaml
  tekton/ci-workspace/jobs/tekton-image-build.yaml
  tekton/ci-workspace/plumbing/template.yaml
  tekton/ci-workspace/shared/common-tasks.yaml
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/jobs/tasks.yaml
  tekton/ci/jobs/tekton-image-build.yaml
  tekton/ci/templates/plumbing-template.yaml
Labels: approved, kind/misc, lgtm, size/XL
