Repository tektoncd/plumbing, pull requests merged in 2021-06, with the labels that each got.

#847 Bump tkn version to v0.19.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#846 Add Results CI trigger to tektonci dogfooding eventlistener.
  tekton/ci/eventlistener.yaml
Labels: approved, kind/misc, lgtm, size/XS

#845 Results API: Add GCP LB specific annotations + resources.
  tekton/cd/results/README.md
  tekton/cd/results/base/kustomization.yaml
  tekton/cd/results/overlays/dogfooding/bec.yaml
  tekton/cd/results/overlays/dogfooding/kustomization.yaml
  tekton/cd/results/overlays/dogfooding/service.yaml
Labels: approved, kind/bug, lgtm, size/M

#848 Increase Dashboard nightly timeout to 1h30m
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
Labels: approved, kind/misc, lgtm, size/XS

#851 [github-simple] Use prow OWNERS config for comment approval OWNERS file.
  tekton/ci/interceptors/github/README.md
  tekton/ci/interceptors/github/go.mod
  tekton/ci/interceptors/github/go.sum
  tekton/ci/interceptors/github/pkg/github/issue_comment.go
  tekton/ci/interceptors/github/pkg/github/issue_comment_test.go
  tekton/ci/interceptors/github/pkg/github/testdata/TESTOWNERS
Labels: approved, kind/feature, lgtm, size/L

#849 Document the scripts in the hack directory
  DEVELOPMENT.md
  hack/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/M

#850 [github-simple] Move resources to tekton-ci namespace.
  tekton/ci/interceptors/github/config/service.yaml
Labels: approved, kind/misc, lgtm, size/XS

#854 Fix the check-pr-kind CI job by restoring HOME
  tekton/ci/jobs/tasks.yaml
Labels: approved, kind/bug, lgtm, size/XS

#855 Change mount location for ppc64le nightly tests
  tekton/resources/nightly-tests/bastion-p/deploy_tekton_pipeline.yaml
  tekton/resources/nightly-tests/bastion-p/deploy_tekton_triggers.yaml
  tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#857 Fix the cp command in the release publish task
  tekton/ci/interceptors/add-pr-body/tekton/publish.yaml
  tekton/ci/interceptors/add-team-members/tekton/publish.yaml
Labels: approved, kind/bug, lgtm, size/XS

#858 Stop using spec.serviceType in event listeners
  tekton/ci/interceptors/github/examples/trigger.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
Labels: approved, kind/misc, lgtm, size/XS

#859 Catlin: Generate warning when using secretKeyRef in env
  catlin/pkg/validator/task_validator.go
  catlin/pkg/validator/task_validator_test.go
Labels: approved, kind/misc, lgtm, ok-to-test, size/M

#860 update tkn version to 0.19.1
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS
