Repository tektoncd/plumbing, pull requests merged in 2021-09, with the labels that each got.

#882 Bump golangci-lint to v1.42.0.
  tekton/images/test-runner/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#883 results dogfooding: Use external DNS hostname in watcher.
  tekton/cd/results/overlays/dogfooding/kustomization.yaml
  tekton/cd/results/overlays/dogfooding/watcher.yaml
Labels: kind/feature, lgtm, approved, size/S

#889 Record that Alan Greene has access to our clusters 📝
  bots/buildcaptain/README.md
Labels: lgtm, approved, size/XS, kind/misc

#892 Remove sbwsg from rotation and owners
  OWNERS
  bots/buildcaptain/README.md
  bots/buildcaptain/rotation.csv
Labels: lgtm, approved, size/L, kind/misc

#893 Use ko v0.9.1
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#894 add chains coverage to prow
  prow/config.yaml
Labels: kind/feature, lgtm, approved, size/M

#877 Add option to build multi-arch images using ko tool
  tekton/resources/images/docker-multi-arch-template.yaml
  tekton/resources/images/eventlistener.yaml
  tekton/resources/images/ko-multi-arch-template.yaml
  tekton/resources/images/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/M

#891 Add tekton-results-viewer service account.
  tekton/cd/results/overlays/dogfooding/kustomization.yaml
  tekton/cd/results/overlays/dogfooding/rbac.yaml
Labels: lgtm, approved, size/S, kind/misc

#896 Update ko to v0.9.2
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc
