Repository tektoncd/plumbing, pull requests merged in 2021-07, with the labels that each got.

#852 Add nightly e2e dashboard test for ppc64le
  docs/dogfooding.md
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/kustomization.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/kustomization.yaml
  tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml
  tekton/resources/nightly-tests/bastion-p/kustomization.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
  tekton/resources/nightly-tests/kustomization.yaml
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#862 Fix Dashboard nightly builds
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
Labels: approved, kind/misc, lgtm, size/XS

#861 Add platforms annotation verification to Catlin
  catlin/README.md
  catlin/pkg/consts/consts.go
  catlin/pkg/validator/content_validator.go
  catlin/pkg/validator/validate_test.go
Labels: approved, kind/feature, lgtm, size/L

#863 Add HOME env to create-release-draft step template
  tekton/resources/release/base/github_release.yaml
Labels: approved, kind/bug, lgtm, size/XS

#864 update tkn version to 0.20.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#868 community#418: Add org.yaml peribolos validation 🧙
  tekton/ci-workspace/community/template.yaml
  tekton/ci-workspace/jobs/kustomization.yaml
  tekton/ci-workspace/jobs/tekton-org-validation.yaml
Labels: approved, kind/feature, lgtm, size/L

#869 Update peribolos-dry-run task to use workspaces
  tekton/ci-workspace/jobs/tekton-org-validation.yaml
Labels: approved, kind/bug, lgtm, size/XS
