Repository tektoncd/plumbing, pull requests merged in 2021-11, with the labels that each got.

#914 Add cronjobs to the dashboard
  tekton/cd/dashboard/overlays/dogfooding/extensions.yaml
  tekton/cd/dashboard/overlays/dogfooding/kustomization.yaml
Labels: lgtm, approved, size/M, kind/misc

#917 Pin ko to 0.8.3
  tekton/images/test-runner/Dockerfile
Labels: kind/bug, lgtm, approved, size/XS

#916 Update Dashboard nightly release template
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
Labels: lgtm, approved, size/M, kind/misc

#919 Update Dashboard nightly release storage request
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#918 Match iterator TaskLoop variable to match kaniko param
  tekton/ci-workspace/jobs/tekton-image-build.yaml
Labels: kind/bug, lgtm, approved, size/XS

#922 Add a python unit tests job to the website
  tekton/ci-workspace/jobs/kustomization.yaml
  tekton/ci-workspace/jobs/tekton-python-unit-tests.yaml
  tekton/ci-workspace/kustomization.yaml
  tekton/ci-workspace/website/kustomization.yaml
  tekton/ci-workspace/website/template.yaml
  tekton/ci-workspace/website/trigger.yaml
Labels: kind/feature, lgtm, approved, size/L

#923 Add diff-task job
  tekton/ci-workspace/catalog/template.yaml
  tekton/ci-workspace/catalog/trigger.yaml
  tekton/ci-workspace/jobs/tekton-catalog-diff-task.yaml
Labels: kind/feature, lgtm, approved, size/L

#925 Add tekton diff job in kustomization
  tekton/ci-workspace/jobs/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#924 Improve python tooling for adjustpermissions.py
  .gitignore
  adjustpermissions.py
  docs/README.md
  requirements.txt
Labels: lgtm, approved, size/S, kind/cleanup

#928 Add lbernick to buildcaptain rotation
  bots/buildcaptain/rotation.csv
Labels: lgtm, approved, size/M, kind/misc
