Repository tektoncd/plumbing, pull requests merged in 2021-02, with the labels that each got.

#699 Add yaml based e2e tests to s390x test pipeline
  tekton/resources/nightly-tests/bastion-z/deploy_test_cleanup.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-template.yaml
Labels: approved, kind/misc, lgtm, size/S

#705 Use generateName instead of $(uid) in templates
  tekton/ci/README.md
  tekton/ci/templates/all-template.yaml
  tekton/ci/templates/community-template.yaml
  tekton/ci/templates/plumbing-template.yaml
  tekton/ci/templates/tekton-cd-template.yaml
  tekton/ci/templates/website-template.yaml
  tekton/resources/cd/cleanup-template.yaml
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/folder-template.yaml
  tekton/resources/cd/helm-template.yaml
  tekton/resources/cd/notification-template.yaml
  tekton/resources/cd/tekton-template.yaml
  tekton/resources/ci/github-template.yaml
  tekton/resources/images/multi-arch-template.yaml
  tekton/resources/images/single-arch-template.yaml
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
  tekton/resources/release/nightly-release-logs-trigger.yaml
Labels: approved, kind/misc, lgtm, size/M

#707 Update plumbing reference from master to main 🪄
  DEVELOPMENT.md
  adjustpermissions.py
  bots/buildcaptain/README.md
  bots/buildcaptain/cmd/buildcaptain/main.go
  bots/buildcaptain/go.sum
  docs/dogfooding.md
  label_sync/README.md
  label_sync/labels.yaml
  scripts/deploy-release.sh
  tekton/cronjobs/README.md
  tekton/cronjobs/bases/configmap/trigger-resource-cd.yaml
  tekton/cronjobs/bases/folder/trigger-resource-cd.yaml
  tekton/cronjobs/bases/image-build/trigger-image-build.yaml
  tekton/cronjobs/bases/tekton-service/trigger-resource-cd.yaml
  tekton/cronjobs/dogfooding/configmaps/labels-sync-hourly/cronjob.yaml
  tekton/cronjobs/dogfooding/configmaps/prow-config-hourly/cronjob.yaml
  tekton/cronjobs/dogfooding/configmaps/prow-labels-sync-hourly/cronjob.yaml
  tekton/cronjobs/dogfooding/configmaps/prow-plugins-hourly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/alpine-git-nonroot-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/coverage-image-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/hub-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/ko-gcloud-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/ko-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/kubectl-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/openssh-server-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/pipeline-test-runner-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/skopeo-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/tkn-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/yamllint-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-robocat/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton/cronjob.yaml
  tekton/cronjobs/robocat/manifests/cadmin-nightly/cronjob.yaml
  tekton/cronjobs/robocat/manifests/certificates-on-demand/cronjob.yaml
  tekton/cronjobs/robocat/manifests/plumbing-tekton-resources-nightly/cronjob.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-template.yaml
  tekton/resources/release/README.md
Labels: approved, kind/cleanup, lgtm, size/M

#709 Remove unused git resource from label check
  tekton/ci/jobs/tasks.yaml
  tekton/ci/jobs/tekton-kind-label.yaml
  tekton/ci/templates/all-template.yaml
Labels: approved, kind/misc, lgtm, size/S

#710 Allow to update resources from tekton/resources in different namespaces
  tekton/cronjobs/robocat/manifests/plumbing-tekton-resources-nightly/cronjob.yaml
Labels: approved, kind/misc, lgtm, size/XS

#696 Hot reload the build captain csv 🔥
  bots/buildcaptain/cmd/buildcaptain/main.go
Labels: approved, kind/cleanup, lgtm, size/S

#712 Fix the check labels job
  tekton/ci/jobs/tasks.yaml
  tekton/ci/jobs/tekton-kind-label.yaml
  tekton/ci/templates/all-template.yaml
Labels: approved, kind/misc, lgtm, size/M

#713 Fix the path to labels.yaml in the check labels job
  tekton/ci/jobs/tasks.yaml
Labels: approved, kind/bug, lgtm, size/XS

#717 Generate a buildcaptain rotation for 2021
  bots/buildcaptain/rotation-overrides.csv
  bots/buildcaptain/rotation.csv
Labels: approved, kind/misc, lgtm, size/L

#706 Update community reference from master to main 🪄
  CONTRIBUTING.md
  README.md
  adjustpermissions.py
  catlin/README.md
  docs/README.md
  tekton/cronjobs/dogfooding/images/teps-community-nightly/cronjob.yaml
  tekton/resources/org-permissions/README.md
  tekton/resources/org-permissions/peribolos-trigger.yaml
Labels: approved, kind/cleanup, lgtm, size/M

#711 CronJob to enable nightly build for Catlin
  tekton/cronjobs/dogfooding/images/catlin-nightly/README.md
  tekton/cronjobs/dogfooding/images/catlin-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/catlin-nightly/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/M

#719 Bump tkn to v0.16.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#708 Add observability configuration to pipeline
  tekton/cd/pipeline/overlays/dogfooding/config-observability.yaml
  tekton/cd/pipeline/overlays/dogfooding/controller.yaml
  tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
  tekton/cd/pipeline/overlays/dogfooding/webhook.yaml
Labels: approved, kind/misc, lgtm, size/S

#720 Add labels to the github template
  tekton/ci/README.md
  tekton/resources/ci/github-template.yaml
Labels: approved, kind/misc, lgtm, size/S

#721 Add catlin-nightly to kustomize
  tekton/cronjobs/dogfooding/images/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#714 Refactor nightly builds
  tekton/ci/0001_rbac.yaml
  tekton/cronjobs/bases/release/trigger-with-uuid.yaml
  tekton/cronjobs/dogfooding/releases/dashboard-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/triggers-nightly/cronjob.yaml
  tekton/images/kubectl/Dockerfile
  tekton/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/cd/serviceaccount.yaml
  tekton/resources/nightly-release/README.md
  tekton/resources/nightly-release/base/bindings.yaml
  tekton/resources/nightly-release/base/eventlistener.yaml
  tekton/resources/nightly-release/base/kustomization.yaml
  tekton/resources/nightly-release/base/kustomizeconfig/eventlistener.yaml
  tekton/resources/nightly-release/base/kustomizeconfig/pipeline.yaml
  tekton/resources/nightly-release/base/trigger.yaml
  tekton/resources/nightly-release/bindings.yaml
  tekton/resources/nightly-release/eventlistener.yaml
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/dashboard/bindings.yaml
  tekton/resources/nightly-release/overlays/dashboard/kustomization.yaml
  tekton/resources/nightly-release/overlays/dashboard/trigger.yaml
  tekton/resources/nightly-release/overlays/pipeline/bindings.yaml
  tekton/resources/nightly-release/overlays/pipeline/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline/trigger.yaml
  tekton/resources/nightly-release/overlays/triggers/bindings.yaml
  tekton/resources/nightly-release/overlays/triggers/kustomization.yaml
  tekton/resources/nightly-release/overlays/triggers/trigger.yaml
  tekton/resources/nightly-release/serviceaccount.yaml
  tekton/resources/nightly-release/tasks.yaml
Labels: approved, kind/misc, lgtm, size/L

#724 Add git to the kubectl image
  tekton/images/kubectl/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#726 Fix CONTEXT_PATH in catlin CronJob
  tekton/cronjobs/dogfooding/images/catlin-nightly/cronjob.yaml
Labels: approved, kind/misc, lgtm, size/XS

#728 Catlin: Fix Dockerfile
  catlin/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#725 Add k8s cluster management task to s390x test setup
  docs/dogfooding.md
  tekton/cronjobs/bases/nightly-tests/trigger-nightly-test.yaml
  tekton/cronjobs/dogfooding/nightly-tests/pipeline-nightly-test/cronjob.yaml
  tekton/resources/nightly-tests/bastion-z/cleanup_tekton.yaml
  tekton/resources/nightly-tests/bastion-z/deploy_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-z/deploy_test_cleanup.yaml
  tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml
  tekton/resources/nightly-tests/bastion-z/kustomization.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
  tekton/resources/nightly-tests/kustomization.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
Labels: approved, kind/feature, lgtm, size/XL

#730 Add koparse image for build pipelines
  tekton/cronjobs/dogfooding/images/koparse-nightly/README.md
  tekton/cronjobs/dogfooding/images/koparse-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/koparse-nightly/kustomization.yaml
  tekton/images/koparse/Dockerfile
  tekton/images/koparse/koparse/__pycache__/koparse.cpython-38.pyc
  tekton/images/koparse/koparse/koparse.py
  tekton/images/koparse/koparse/test_koparse.py
  tekton/images/koparse/koparse/test_release.yaml
Labels: approved, kind/feature, lgtm, size/XL

#729 Add DNS manager docs and annotations
  docs/dogfooding.md
  tekton/cd/dashboard/overlays/dogfooding/ingress.yaml
  tekton/cd/dashboard/overlays/robocat/ingress.yaml
  tekton/ci/ingress.yaml
  tekton/mario-bot/ingress.yaml
Labels: approved, kind/documentation, lgtm, size/M

#727 Fix: Catlin validate command
  catlin/pkg/validator/task_validator.go
  catlin/pkg/validator/task_validator_test.go
Labels: approved, kind/bug, lgtm, size/XS

#733 Remove gcs-fetcher from nightly release
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#734 Add legacy tasks to plumbing releases
  tekton/resources/nightly-release/tasks.yaml
Labels: approved, kind/misc, lgtm, size/L

#735 Only try to fetch team members if team key is present in body
  tekton/ci/interceptors/add-team-members/README.md
  tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go
  tekton/ci/interceptors/add-team-members/cmd/add-team-members/main_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/M

#731 Add Catlin to Catalog CI
  tekton/ci/eventlistener.yaml
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/jobs/tekton-catlin-lint.yaml
  tekton/ci/templates/catalog-template.yaml
  tekton/ci/templates/kustomization.yaml
Labels: approved, kind/feature, lgtm, size/L

#738 Run the new pipeline nightlies
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: approved, kind/misc, lgtm, size/M

#736 Rework the prerelease-check task to use workspaces
  tekton/resources/release/prerelease_checks.yaml
Labels: approved, kind/misc, lgtm, size/M

#741 Remove check-kind-label check from catalog
  tekton/ci/eventlistener.yaml
Labels: approved, kind/misc, lgtm, size/XS

#742 List all members of the org, not just public members
  tekton/ci/interceptors/add-team-members/README.md
  tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/S

#737 Try to find team key in the right place of the payload
  tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#739 Fix the pipeline run for pipeline nightly
  .gitignore
  tekton/resources/nightly-release/README.md
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/tasks.yaml
  tekton/resources/release/base/github_release.yaml
  tekton/resources/release/base/install_and_test_tekton_release.yaml
  tekton/resources/release/base/install_tekton_release.yaml
  tekton/resources/release/base/kustomization.yaml
  tekton/resources/release/base/nightly-release-logs-trigger.yaml
  tekton/resources/release/base/prerelease_checks.yaml
  tekton/resources/release/base/save-release-logs.yaml
  tekton/resources/release/base/test_tekton_release.yaml
  tekton/resources/release/kustomization.yaml
  tekton/resources/release/overlays/default/kustomization.yaml
  tekton/resources/release/overlays/tekton-nightly/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/L
