Repository tektoncd/plumbing, pull requests merged in 2021-12, with the labels that each got.

#930 Fix operator nightly tests for s390x and ppc64le
  tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#933 Update kubectl to a more recent version
  tekton/images/kubectl/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#939 Give mariobot SA access to clusterinterceptors
  tekton/mario-bot/mario-image-build-trigger.yaml
Labels: lgtm, approved, size/XS, kind/misc

#940 Ignore warnings when deploying resources
  tekton/resources/cd/folder-template.yaml
Labels: kind/bug, lgtm, approved, size/XS

#927 Setup e2e tests on kind
  tekton/ci-workspace/jobs/e2e-kind.yaml
  tekton/ci-workspace/jobs/kustomization.yaml
  tekton/ci-workspace/kustomization.yaml
  tekton/ci-workspace/pipeline/kustomization.yaml
  tekton/ci-workspace/pipeline/template.yaml
  tekton/ci-workspace/pipeline/trigger.yaml
  tekton/ci/README.md
  tekton/cronjobs/dogfooding/images/kind-e2e-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/kind-e2e-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/images/kustomization.yaml
  tekton/images/kind-e2e/Dockerfile
  tekton/images/kind-e2e/setup-kind.sh
Labels: kind/feature, size/XL, lgtm, approved

#943 Detect git clone tasks in the tekton-events el
  tekton/resources/cd/eventlistener.yaml
Labels: lgtm, approved, size/XS, kind/misc

#926 Add GCP Viewer role to adjustpermissions.py
  adjustpermissions.py
Labels: lgtm, approved, size/S, kind/misc

#942 Fix the file regex for kind e2e
  tekton/ci-workspace/pipeline/template.yaml
Labels: kind/bug, lgtm, approved, size/XS

#946 Cleanup unused resources from tekton/ci
  tekton/ci/templates/kustomization.yaml
  tekton/ci/templates/tekton-cd-template.yaml
  tekton/ci/templates/website-template.yaml
Labels: lgtm, approved, size/M, kind/misc

#944 Use alpha features in pipeline and triggers
  tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
  tekton/cd/triggers/overlays/dogfooding/feature-flags.yaml
  tekton/cd/triggers/overlays/dogfooding/kustomization.yaml
Labels: lgtm, approved, size/S, kind/misc

#947 Fix the name of the pipeline test script in kind e2e
  tekton/ci-workspace/pipeline/template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#948 Migrate label check to ci-workspace
  tekton/ci-workspace/jobs/kustomization.yaml
  tekton/ci-workspace/jobs/tekton-kind-label.yaml
  tekton/ci-workspace/shared/template.yaml
  tekton/ci-workspace/shared/trigger.yaml
  tekton/ci/eventlistener.yaml
  tekton/ci/jobs/tasks.yaml
  tekton/ci/jobs/tekton-kind-label.yaml
  tekton/ci/templates/all-template.yaml
  tekton/ci/templates/kustomization.yaml
Labels: lgtm, approved, size/L, kind/misc

#950 Fix the kustomise file in tekton/ci
  tekton/ci/jobs/kustomization.yaml
Labels: kind/bug, lgtm, approved, size/XS

#936 Rewrite MarioBot to use Pipelines and Workspaces
  bots/mariobot/README.md
  tekton/mario-bot/mario-github-comment.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
Labels: lgtm, approved, size/L, kind/cleanup

#952 Deploy labels to tekton-ci
  tekton/cronjobs/dogfooding/configmaps/labels-sync-hourly/cronjob.yaml
Labels: lgtm, approved, size/XS, kind/misc

#954 Use the correct account to deploy labels to tekton-ci
  tekton/cronjobs/dogfooding/configmaps/labels-sync-hourly/cronjob.yaml
Labels: lgtm, approved, size/XS, kind/misc

#955 Fix the migrated yamllint job
  tekton/ci/jobs/tekton-yamllint.yaml
Labels: lgtm, approved, size/S, kind/misc

#957 Fix kustomize for cronjobs
  tekton/cronjobs/dogfooding/cleanup/kustomization.yaml
  tekton/cronjobs/dogfooding/images/kustomization.yaml
Labels: kind/bug, lgtm, approved, size/XS

#960 Fix a few more issues related to the removal of tektonci
  tekton/ci/pipeline/trigger.yaml
  tekton/ci/plumbing/trigger.yaml
  tekton/ci/shared/trigger.yaml
  tekton/ci/website/trigger.yaml
Labels: kind/bug, lgtm, approved, size/S

#961 Fix the hub container image
  tekton/images/hub/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#962 Fix the image build CI job
  tekton/ci/jobs/tekton-image-build.yaml
Labels: kind/bug, lgtm, approved, size/M

#959 Add pipeline to run s390x catalog tests
  tekton/cronjobs/dogfooding/nightly-tests/s390x/catalog-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/s390x/catalog-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/catalog-nightly-test/kustomization.yaml
  tekton/resources/nightly-tests/README.md
  tekton/resources/nightly-tests/catalog-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
  tekton/resources/nightly-tests/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/L

#964 Add catalog s390x nightly test cronjob to kustomization config
  tekton/cronjobs/dogfooding/nightly-tests/s390x/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#956 Use TriggerGroups for CI Jobs 🥳
  tekton/ci/README.md
  tekton/ci/catalog/template.yaml
  tekton/ci/catalog/trigger.yaml
  tekton/ci/community/trigger.yaml
  tekton/ci/pipeline/trigger.yaml
  tekton/ci/plumbing/trigger.yaml
  tekton/ci/shared/eventlistener.yaml
  tekton/ci/shared/trigger.yaml
  tekton/ci/website/trigger.yaml
Labels: kind/feature, size/XL, lgtm, approved

#965 Migrate CI event listener to v1beta1
  tekton/ci/shared/eventlistener.yaml
Labels: lgtm, approved, size/XS, kind/misc

#966 Fix github CI secret name
  tekton/ci/shared/eventlistener.yaml
Labels: lgtm, approved, size/XS, kind/misc

#969 Reduce the likelyhood of pending CI jobs
  tekton/resources/ci/github-template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#968 Move the custom interceptor out of trigger groups
  tekton/ci/community/trigger.yaml
  tekton/ci/pipeline/trigger.yaml
  tekton/ci/plumbing/trigger.yaml
  tekton/ci/shared/eventlistener.yaml
  tekton/ci/shared/trigger.yaml
  tekton/ci/website/trigger.yaml
Labels: lgtm, approved, size/M, kind/misc

#973 CI Interceptors: Use Environment Variables instead of Parameters
  tekton/ci/interceptors/add-pr-body/tekton/publish.yaml
  tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml
  tekton/ci/interceptors/add-team-members/tekton/publish.yaml
  tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml
Labels: lgtm, approved, size/L

#974 CI Jobs: Use Environment Variables instead of Parameters
  tekton/ci/jobs/tekton-catalog-catlin-lint.yaml
  tekton/ci/jobs/tekton-kind-label.yaml
Labels: lgtm, approved, size/S

#975 CI Shared: Use Environment Variables instead of Parameters
  tekton/ci/shared/common-tasks.yaml
Labels: lgtm, approved, size/S

#976 Mario Bot: Use Environment Variables instead of Parameters
  tekton/mario-bot/mario-github-comment.yaml
Labels: lgtm, approved, size/S
