Repository tektoncd/plumbing, pull requests merged in 2021-04, with the labels that each got.

#795 Modify triggers nightly trigger template
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: approved, kind/misc, lgtm, size/M

#802 Fix handling of condition tasks in CI
  tekton/ci-workspace/README.md
  tekton/resources/cd/eventlistener.yaml
Labels: approved, kind/bug, lgtm, size/S

#798 Update the triggers install in tekton_in_kind
  hack/tekton_in_kind.sh
Labels: approved, kind/misc, lgtm, size/M

#805 Rename check-kind-label to kind-label
  tekton/ci-workspace/README.md
  tekton/ci/README.md
  tekton/ci/jobs/tasks.yaml
  tekton/ci/jobs/tekton-kind-label.yaml
Labels: approved, kind/bug, lgtm, size/S

#796 Bump tkn version to v0.17.1
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/feature, lgtm, size/XS

#804 Add script linting to catlin catalog check job
  catlin/Dockerfile
  tekton/ci/jobs/tekton-catlin-lint.yaml
Labels: approved, kind/misc, lgtm, size/S

#807 Fix kind script in a few places
  hack/tekton_in_kind.sh
Labels: approved, kind/misc, lgtm, size/XS

#809 Bump images to use tkn 0.17.2
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#808 Fix catlin script lint job
  tekton/ci/jobs/tekton-catlin-lint.yaml
Labels: approved, kind/misc, lgtm, size/S

#789 Add pipeline to run s390x dashboard tests
  tekton/cronjobs/dogfooding/nightly-tests/s390x/dashboard-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/s390x/dashboard-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/dashboard-nightly-test/kustomization.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/kustomization.yaml
  tekton/resources/nightly-tests/README.md
  tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
  tekton/resources/nightly-tests/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/L

#791 Add RoleBinding to cleanup pr/tr from bastion-p namespace
  tekton/resources/cd/serviceaccount.yaml
Labels: approved, kind/bug, lgtm, ok-to-test, size/S

#782 Add a pipeline to request doc reviewers
  docs/README.md
  tekton/ci-workspace/jobs/kustomization.yaml
  tekton/ci-workspace/jobs/tekton-docs-reviews.yaml
  tekton/ci-workspace/shared/template.yaml
  tekton/ci-workspace/shared/trigger.yaml
Labels: approved, kind/feature, lgtm, size/L

#797 Fix the plumbing template
  tekton/ci-workspace/plumbing/trigger.yaml
  tekton/ci-workspace/shared/bindings.yaml
Labels: approved, kind/bug, lgtm, size/S

#692 Add Makefile for Catlin
  catlin/.gitignore
  catlin/Makefile
  catlin/go.sum
  catlin/pkg/parser/parser.go
Labels: approved, kind/feature, lgtm, size/M

#812 Add more space to s390x dashboard integration test
  tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
Labels: approved, kind/bug, lgtm, size/XS

#813 Add 'patch' privillege to tekton-deployer sa
  robocat/cadmin/200-rbac.yaml
Labels: approved, kind/misc, lgtm, size/XS

#814 Add post release file to Tekton install task and script
  robocat/cadmin/200-rbac.yaml
  scripts/README.md
  scripts/deploy-release.sh
  tekton/cronjobs/bases/tekton-service/trigger-resource-cd.yaml
  tekton/resources/cd/bindings.yaml
  tekton/resources/cd/tekton-template.yaml
  tekton/resources/release/base/install_tekton_release.yaml
Labels: approved, kind/misc, lgtm, size/M

#815 Add the clusterinterceptors to clusterroles
  tekton/ci-workspace/infra/0001_rbac.yaml
  tekton/ci/0001_rbac.yaml
  tekton/resources/cd/serviceaccount.yaml
  tekton/resources/nightly-release/serviceaccount.yaml
  tekton/resources/nightly-tests/serviceaccount.yaml
Labels: approved, kind/misc, lgtm, size/M

#817 Add feature flags config to pipeline overlay
  tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#816 Stop using depreacted replicas in event listeners
  tekton/resources/cd/eventlistener.yaml
Labels: approved, kind/misc, lgtm, size/XS

#818 e2e-test.sh: Pin cluster version to GKE 1.18.
  scripts/e2e-tests.sh
Labels: approved, kind/misc, lgtm, size/XS

#819 Pin GKE cluster version for e2e tests
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, kind/misc, lgtm, size/XS

#820 Pin version to regular channel
  scripts/library.sh
Labels: approved, kind/misc, lgtm, size/XS

#806 GitHub interceptor - Simplified GitHub configuration.
  tekton/ci/interceptors/github/README.md
  tekton/ci/interceptors/github/config/clustertriggerbindings.yaml
  tekton/ci/interceptors/github/config/service.yaml
  tekton/ci/interceptors/github/examples/trigger.yaml
  tekton/ci/interceptors/github/go.mod
  tekton/ci/interceptors/github/go.sum
  tekton/ci/interceptors/github/main.go
  tekton/ci/interceptors/github/pkg/github/bindings/bindings.go
  tekton/ci/interceptors/github/pkg/github/config.go
  tekton/ci/interceptors/github/pkg/github/issue_comment.go
  tekton/ci/interceptors/github/pkg/github/issue_comment_test.go
  tekton/ci/interceptors/github/pkg/github/pull_request.go
  tekton/ci/interceptors/github/pkg/github/pull_request_test.go
  tekton/ci/interceptors/github/pkg/github/push.go
  tekton/ci/interceptors/github/pkg/github/push_test.go
  tekton/ci/interceptors/github/pkg/github/server.go
  tekton/ci/interceptors/github/pkg/github/server_test.go
  tekton/ci/interceptors/github/pkg/github/status.go
  tekton/ci/interceptors/github/pkg/github/testdata/issue_comment.json
  tekton/ci/interceptors/github/pkg/github/testdata/pull_request.json
  tekton/ci/interceptors/github/pkg/github/testdata/push.json
  tekton/ci/interceptors/github/pkg/proto/v1alpha1/config.proto
  tekton/ci/interceptors/github/pkg/proto/v1alpha1/config_go_proto/config.pb.go
  tekton/ci/interceptors/github/pkg/proto/v1alpha1/gen.go
Labels: approved, kind/feature, lgtm, size/XXL

#811 Remove --enable-basic-auth from e2e test clusters.
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, kind/misc, lgtm, size/M

#822 bump tkn version to v0.18.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: approved, kind/misc, lgtm, size/XS

#823 GitHub Simple Interceptor: Standardize naming, fix webhook validation.
  tekton/ci/interceptors/github/README.md
  tekton/ci/interceptors/github/config/service.yaml
  tekton/ci/interceptors/github/main.go
  tekton/ci/interceptors/github/pkg/github/server.go
Labels: approved, kind/bug, lgtm, size/M
