Repository tektoncd/plumbing, pull requests merged in 2022-09, with the labels that each got.

#1191 Move Dashboard integration tests from GKE to Kind
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1195 Enable privileged mode for the Dashboard integration test container
  docs/kind-e2e.md
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1194 tektoncd/results: use golang 1.18
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1197 Use squash for chains merge method.
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1198 Bump tkn to v0.26.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1193 Migrate s390x jobs to ibmcloud
  tekton/cronjobs/dogfooding/nightly-tests/s390x/catalog-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/cli-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/dashboard-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/pipeline-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/s390x/triggers-nightly-test/cronjob.yaml
  tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml
  tekton/resources/nightly-tests/catalog-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Labels: kind/feature, lgtm, approved, size/L, ok-to-test

#1201 Update test-runner image in Prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1200 Add cherrypicker deployment
  docs/prow.md
  prow/README.md
  prow/plugins.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1199 Add broker manifest
  docs/dogfooding.md
Labels: lgtm, approved, size/S, kind/documentation

#1185 Add new pr-commenter custom task
  .gitignore
  tekton/ci/custom-tasks/pr-commenter/.golangci.yml
  tekton/ci/custom-tasks/pr-commenter/Makefile
  tekton/ci/custom-tasks/pr-commenter/README.md
  tekton/ci/custom-tasks/pr-commenter/cmd/pr-commenter/kodata/LICENSE
  tekton/ci/custom-tasks/pr-commenter/cmd/pr-commenter/main.go
  tekton/ci/custom-tasks/pr-commenter/config/200-serviceaccount.yaml
  tekton/ci/custom-tasks/pr-commenter/config/201-clusterrole.yaml
  tekton/ci/custom-tasks/pr-commenter/config/201-role.yaml
  tekton/ci/custom-tasks/pr-commenter/config/201-rolebinding.yaml
  tekton/ci/custom-tasks/pr-commenter/config/202-clusterrolebinding.yaml
  tekton/ci/custom-tasks/pr-commenter/config/500-controller.yaml
  tekton/ci/custom-tasks/pr-commenter/go.mod
  tekton/ci/custom-tasks/pr-commenter/go.sum
  tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/controller.go
  tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/params.go
  tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/params_test.go
  tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/reconciler.go
  tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/reconciler_test.go
  tekton/ci/custom-tasks/pr-commenter/tekton/README.md
  tekton/ci/custom-tasks/pr-commenter/tekton/kustomization.yaml
  tekton/ci/custom-tasks/pr-commenter/tekton/publish.yaml
  tekton/ci/custom-tasks/pr-commenter/tekton/release-pipeline.yaml
  tekton/ci/custom-tasks/pr-commenter/tools/go.mod
  tekton/ci/custom-tasks/pr-commenter/tools/tools.go
  tekton/ci/repos/plumbing/template.yaml
  tekton/cronjobs/dogfooding/releases/pr-commenter-nightly/README.md
  tekton/cronjobs/dogfooding/releases/pr-commenter-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pr-commenter-nightly/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/template.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/trigger.yaml
Labels: kind/feature, lgtm, approved, size/XXL

#1202 Tuning the tekton-admin service account
  tekton/resources/cd/serviceaccount.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1203 Fix the resource deployment
  tekton/resources/cd/folder-template.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1134 nightlies: update operator nightly pipelinerun
  tekton/resources/nightly-release/overlays/operator/template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1207 Make resources path writeable earlier
  tekton/resources/cd/folder-template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1208 Add pr-commenter to dogfooding releases kustomization.yaml
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1209 Don't fail deploy-from-folder when there's nothing changed
  tekton/resources/cd/folder-template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1210 prow/config: only set docker-in-docker with labels
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1215 Update dogfooding ClusterIssuer to v1
  tekton/certificates/clusterissuer.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1217 Document how to restore kafka
  docs/dogfooding.md
Labels: lgtm, approved, size/S, kind/documentation

#1214 Add docker-in-docker image to fix Ci issue in s390x dogfooding cluster
  tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
Labels: lgtm, approved, size/M, ok-to-test, kind/misc

#1220 Turn on PRCommenter on completion of PR builds
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/ci/bindings.yaml
  tekton/resources/ci/github-template.yaml
Labels: kind/feature, lgtm, approved, size/M

#1224 Add missing pr-status-updater config
  tekton/ci/repos/plumbing/template.yaml
  tekton/cronjobs/dogfooding/releases/pr-status-updater-nightly/README.md
  tekton/cronjobs/dogfooding/releases/pr-status-updater-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pr-status-updater-nightly/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/template.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/trigger.yaml
Labels: kind/feature, lgtm, approved, size/M, kind/cleanup

#1225 Add `githubCheckIsSuccess` param properly
  tekton/resources/ci/github-template.yaml
Labels: lgtm, approved, size/XS, kind/cleanup

#1226 Cronjob for nightly pr-status-updater release was too long
  tekton/cronjobs/dogfooding/releases/pr-status-updater-nightly/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/cleanup

#1227 Revert turning on PRCommenter in triggers
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/ci/bindings.yaml
  tekton/resources/ci/github-template.yaml
Labels: lgtm, approved, size/M, kind/misc
