Repository tektoncd/plumbing, pull requests merged in 2022-02, with the labels that each got.

#1000 Update Peribolos to the latest version
  tekton/ci/jobs/tekton-org-validation.yaml
  tekton/resources/org-permissions/peribolos.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1001 Update DNS manager version
  docs/dogfooding.md
Labels: lgtm, approved, size/XS, kind/misc

#993 Add pipeline to run ppc64le catalog tests
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/README.md
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/kustomization.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/kustomization.yaml
  tekton/resources/nightly-tests/README.md
  tekton/resources/nightly-tests/catalog-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
  tekton/resources/nightly-tests/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/L, ok-to-test

#1002 Add a label for issues and PR related to the S3C WG
  label_sync/labels.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1004 Fix unbound variables in deploy script
  scripts/deploy-release.sh
Labels: lgtm, approved, size/XS, kind/misc

#1005 Update deprecated v1beta1 ingresses
  docs/README.md
  docs/dogfooding.md
  docs/prow.md
  robocat/README.md
  tekton/cd/dashboard/overlays/dogfooding/ingress.yaml
  tekton/cd/dashboard/overlays/robocat/ingress.yaml
  tekton/cd/results/overlays/dogfooding/ingress.yaml
  tekton/ci/infra/ingress.yaml
  tekton/mario-bot/ingress.yaml
Labels: lgtm, approved, size/L, kind/misc

#1006 Update the tekton deployer role to handle v1 ingresses
  robocat/cadmin/200-rbac.yaml
Labels: lgtm, approved, size/XS, kind/misc
