Repository tektoncd/plumbing, pull requests merged in 2022-04, with the labels that each got.

#1052 Use TriggerGroups and v1beta1 for tekton-events
  tekton/resources/cd/ci-triggers.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/kustomization.yaml
  tekton/resources/cd/notification-triggers.yaml
Labels: kind/feature, lgtm, approved, size/L

#1051 Add pipelines to store job metadata in buckets
  tekton/resources/ci/gubernator-metadata.yaml
  tekton/resources/ci/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/L

#1053 Fix the gubernator resources
  tekton/resources/ci/gubernator-metadata.yaml
Labels: lgtm, approved, size/S, kind/misc

#1054 Migrate trigger objects to v1beta1
  tekton/resources/cd/ci-triggers.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/notification-triggers.yaml
Labels: lgtm, approved, size/L, kind/misc

#1057 Add GitHub proxy deployment to the prow cluster
  docs/prow.md
  prow/gce-ssd-retain_storageclass.yaml
  prow/ghproxy.yaml
Labels: kind/feature, lgtm, approved, size/L

#1058 Update Triggers testrunners to go 1.17.8
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1060 Update Dashboard test-runner images to go 1.17
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1062 Default not readonly & tolerate missing permissions when removing
  adjustpermissions.py
Labels: lgtm, approved, size/S, kind/misc

#1061 Document conditional error with permission script ✍️
  adjustpermissions.py
Labels: lgtm, approved, size/XS, kind/documentation

#1055 Enable nightly builds for Tekton Chains
  tekton/cronjobs/dogfooding/releases/chains-nightly/README.md
  tekton/cronjobs/dogfooding/releases/chains-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/chains-nightly/kustomization.yaml
  tekton/resources/nightly-release/overlays/chains/kustomization.yaml
  tekton/resources/nightly-release/overlays/chains/template.yaml
  tekton/resources/nightly-release/overlays/chains/trigger.yaml
Labels: lgtm, approved, size/M, ok-to-test, kind/misc

#1063 Add basic testgrid config
  prow/config.yaml
  testgrid/config.yaml
  testgrid/default.yaml
Labels: lgtm, approved, size/L, kind/misc

#1065 Fix args for testgrid setup and make non blocking
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1067 Fix args for testgrid postsubmit prow job
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1069 Fix regex triggering TestGrid prow job
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1068 Update pull request template to include kind
  .github/pull_request_template.md
Labels: lgtm, approved, size/XS, kind/misc

#1064 Add chains-nightly to the nightly release list.
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1071 Make TestGrid plumbing presubmit non-optional
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1072 Use correct bucket for chains nightly
  tekton/resources/nightly-release/overlays/chains/template.yaml
Labels: lgtm, approved, size/XS, ok-to-test, kind/misc

#1056 Add template and triggers for gubernator logs
  tekton/ci/infra/0001_rbac.yaml
  tekton/ci/shared/gubernator-metadata.yaml
  tekton/ci/shared/kustomization.yaml
  tekton/resources/cd/ci-triggers.yaml
  tekton/resources/ci/github-gubernator-template.yaml
  tekton/resources/ci/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/L

#1074 Add nightly build for the add-pr-body interceptor
  tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/README.md
  tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-pr-body-ci/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-pr-body-ci/template.yaml
  tekton/resources/nightly-release/overlays/add-pr-body-ci/trigger.yaml
Labels: lgtm, approved, size/M, kind/misc

#1076 Remove wlynch from buildcaptain rotation + regen rotation.
  bots/buildcaptain/README.md
  bots/buildcaptain/rotation.csv
Labels: size/XL, lgtm, approved, kind/misc

#1077 Remove bad unit test
  tekton/ci/cluster-interceptors/add-pr-body/pkg/pr_test.go
Labels: kind/bug, lgtm, approved, size/M
