Repository tektoncd/plumbing, pull requests merged in 2022-08, with the labels that each got.

#1174 Support release "latest" in install tekton release
  tekton/resources/cd/install-tekton-release.yaml
Labels: lgtm, approved, size/S, kind/misc

#1176 prow: bump test-runners to an image that actually uses go 1.18.3.
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1177 Revert "prow: bump test-runners to an image that actually uses go 1.18.3."
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1175 Fix: determine whether the destination path already exists before clone
  tekton/images/test-runner/entrypoint.sh
Labels: kind/bug, lgtm, approved, size/S, ok-to-test

#1179 Update various test-runner images to latest with Go 1.18.3 and golangci-lint 1.47.2
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1182 Enables cherry-pick plugin in prow for tektoncd/operator
  prow/plugins.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1183 Fix a few tiny docs issues
  docs/README.md
  docs/dogfooding.md
Labels: lgtm, approved, size/XS, kind/documentation

#1184 Add kind/security label
  label_sync/labels.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1186 Apply ServiceAccount to the cluster
  tekton/resources/cd/folder-template.yaml
Labels: kind/bug, lgtm, approved, size/S

#1188 Add documentation for using kind for e2e jobs
  docs/README.md
  docs/kind-e2e.md
Labels: lgtm, approved, size/L, kind/documentation

#1190 Add missing feature-flags overlay for Pipelines robocat deploy
  tekton/cd/pipeline/overlays/robocat/feature-flags.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1189 Update language and tools in Dockerfile
  tekton/images/coverage/Dockerfile
  tekton/images/kind-e2e/Dockerfile
  tekton/images/kind/Dockerfile
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/M, kind/misc
