Repository tektoncd/plumbing, pull requests merged in 2022-01, with the labels that each got.

#978 Add a new validation to Catlin to warn about use of params in script blocks
  catlin/pkg/validator/task_validator.go
  catlin/pkg/validator/task_validator_test.go
Labels: lgtm, approved, size/M

#970 Remove the extra labels from the github-set-status
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/ci/bindings.yaml
  tekton/resources/ci/github-template.yaml
Labels: lgtm, approved, size/S, kind/misc

#981 Fix two small issues with catlin script param detection
  catlin/pkg/validator/task_validator.go
  catlin/pkg/validator/task_validator_test.go
Labels: lgtm, approved, size/XS, kind/misc

#977 Sanitize param usage in some plumbing task script blocks
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/folder-template.yaml
  tekton/resources/cd/helm-template.yaml
  tekton/resources/images/docker-multi-arch-template.yaml
  tekton/resources/images/ko-multi-arch-template.yaml
  tekton/resources/nightly-release/tasks.yaml
  tekton/resources/nightly-tests/base/deploy_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml
  tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml
  tekton/resources/release/base/github_release.yaml
  tekton/resources/release/base/install_tekton_release.yaml
  tekton/resources/release/base/prerelease_checks.yaml
Labels: lgtm, approved, size/L, kind/misc

#982 Add back add-pr-body to catalog-issue-comment
  tekton/ci/catalog/trigger.yaml
Labels: kind/bug, lgtm, approved, size/S

#958 Dogfood Pipeline to TaskRun with Mario bot
  tekton/mario-bot/mario-github-comment.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
Labels: lgtm, approved, size/L, kind/misc

#984 Fix a few misplaced "env" in tasks
  tekton/resources/nightly-tests/base/deploy_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml
  tekton/resources/release/base/prerelease_checks.yaml
Labels: kind/bug, lgtm, approved, size/M

#985 Fix missing double quote in check-github-tasks-completed
  tekton/ci/jobs/tekton-github-tasks-completed.yaml
Labels: kind/bug, lgtm, approved, size/XS

#987 Fix kind-label: import os
  tekton/ci/jobs/tekton-kind-label.yaml
Labels: kind/bug, lgtm, approved, size/XS

#988 Fix github-tasks-completed
  tekton/ci/jobs/tekton-github-tasks-completed.yaml
Labels: kind/bug, lgtm, approved, size/XS

#986 Fix k8s cluster creation for s390x tests
  tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml
Labels: kind/bug, lgtm, approved, size/XS

#989 Fix PipelineRef in Operator nightly
  tekton/resources/nightly-release/overlays/operator/template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#991 Add build captain rotation for 2022
  bots/buildcaptain/README.md
  bots/buildcaptain/rotation-overrides.csv
  bots/buildcaptain/rotation.csv
Labels: size/XL, lgtm, approved, kind/misc

#992 Make Scripts Mac-Friendly
  hack/tekton_ci.sh
  hack/tekton_in_kind.sh
  scripts/deploy-release.sh
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
  tekton/cd/pipeline/overlays/robocat/pre/100-inject-minio-creds.sh
Labels: lgtm, approved, size/S

#990 Add extra disk space for dashboard nightly tests to resolve current failure
  tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#997 Update Dockerfiles using golang images to Go 1.16.13
  pipelinerun-logs/Dockerfile
  tekton/images/coverage/Dockerfile
  tekton/images/kind-e2e/Dockerfile
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/kubectl/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#998 Fix single quotes around REGEX
  tekton/ci/shared/common-tasks.yaml
Labels: lgtm, approved, size/XS, kind/misc

#994 Add `catlin bump` feature to bump catalog entries
  catlin/README.md
  catlin/go.mod
  catlin/go.sum
  catlin/pkg/cmd/bump/bump.go
  catlin/pkg/cmd/root.go
  catlin/pkg/entry/entry.go
  catlin/pkg/entry/entry_test.go
  catlin/pkg/entry/version.go
  catlin/pkg/entry/version_test.go
Labels: kind/feature, size/XL, lgtm, approved
