Repository tektoncd/plumbing, pull requests merged in 2022-06, with the labels that each got.

#1086 Add yq YAML parser to ko-gcloud container image
  tekton/images/ko-gcloud/Dockerfile
Labels: lgtm, approved, size/XS, ok-to-test, kind/misc

#1088 prow: move to go 1.17 for tektoncd/operator
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1090 Bump tkn to latest release v0.24.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1092 Add dependencies label
  label_sync/labels.yaml
Labels: kind/feature, lgtm, approved, size/XS

#1084 Update stockout message check in e2e-test.sh
  scripts/e2e-tests.sh
Labels: kind/bug, lgtm, approved, size/XS

#1096 Enable minimal embedded status is alpha integration tests
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1094 Change the release note task for rekor 0.8.2
  tekton/resources/release/base/github_release.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1089 Remove `conditions` from release tooling
  tekton/ci/infra/0001_rbac.yaml
  tekton/resources/cd/serviceaccount.yaml
  tekton/resources/nightly-tests/bastion-z/cleanup_tekton.yaml
  tekton/resources/release/README.md
  tekton/resources/release/base/save-release-logs.yaml
Labels: lgtm, approved, size/S, kind/cleanup

#1097 Add nightly periobolos and fix CI one
  tekton/cronjobs/bases/peribolos/README.md
  tekton/cronjobs/bases/peribolos/kustomization.yaml
  tekton/cronjobs/bases/peribolos/trigger-resource-cd.yaml
  tekton/cronjobs/dogfooding/kustomization.yaml
  tekton/cronjobs/dogfooding/peribolos/kustomization.yaml
  tekton/cronjobs/dogfooding/peribolos/tektoncd/README.md
  tekton/cronjobs/dogfooding/peribolos/tektoncd/cronjob.yaml
  tekton/cronjobs/dogfooding/peribolos/tektoncd/kustomization.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/kustomization.yaml
  tekton/resources/cd/peribolos-template.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
Labels: kind/bug, lgtm, approved, size/L

#1099 Run peribolos daily, not hourly
  tekton/cronjobs/dogfooding/peribolos/tektoncd/cronjob.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1100 Set requests and limits for Pipeline Prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc
