Repository tektoncd/plumbing, pull requests merged in 2022-11, with the labels that each got.

#1251 Use cos_containerd image for testing
  scripts/library.sh
Labels: kind/bug, lgtm, approved, size/XS

#1254 Kind cluster upgrade test
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/cleanup

#1253 Add options for Kubernetes 1.24 and 1.25 to the test-runner kind script
  tekton/images/test-runner/setup-kind.sh
Labels: lgtm, approved, size/S, kind/misc

#1280 Update prow config for upgrade test job
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1279 [Upgrade test] Update config for upgrade test
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1285 tektoncd/operator: switch e2e to use kind…
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1286 Fix operator integration test configuration, cleanup unneeded affinity rules
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/cleanup

#1249 Go coverage Tekton task
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/jobs/tekton-golang-coverage.yaml
  tekton/ci/repos/pipeline/template.yaml
  tekton/ci/shared/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/L

#1223 For tekton/images/tkn build:
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/S, ok-to-test, kind/misc

#1287 Fix the name of the e2e-tests script for operator integration test
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1289 Fix the cronjob deployment job
  tekton/cronjobs/dogfooding/releases/concurrency-nightly/README.md
  tekton/cronjobs/dogfooding/releases/concurrency-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/concurrency-nightly/kustomization.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1291 Bump tkn to latest release v0.28.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc
