Repository tektoncd/plumbing, pull requests merged in 2022-12, with the labels that each got.

#1295 Fix PodSecurity for pr-commenter and pr-status-updater custom tasks
  tekton/ci/custom-tasks/pr-commenter/config/500-controller.yaml
  tekton/ci/custom-tasks/pr-status-updater/config/500-controller.yaml
Labels: lgtm, approved, size/S, kind/misc

#1298 renaming token to bot-token
  tekton/ci/jobs/tekton-golang-coverage.yaml
  tekton/ci/repos/pipeline/template.yaml
Labels: kind/bug, lgtm, approved, size/S

#1302 Add interceptor to trigger roles
  tekton/ci/infra/0001_rbac.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/cd/serviceaccount.yaml
  tekton/resources/nightly-tests/serviceaccount.yaml
Labels: lgtm, approved, size/S, kind/misc

#1303 Fix typo in task definition
  tekton/ci/jobs/tekton-golang-coverage.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1294 Use v1 CronJob for Workflows nightly release
  tekton/cronjobs/dogfooding/releases/workflows-nightly/cronjob.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1305 Remove usage of TaskLoop
  .gitignore
  tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
  tekton/ci/jobs/tekton-golang-tests.yaml
  tekton/ci/jobs/tekton-image-build.yaml
Labels: lgtm, approved, size/M, kind/misc

#1299 Update cert manager to 1.10.1
  tekton/cronjobs/robocat/helm/cert-manager-nightly/cronjob.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1307 Explicitly specify `kind: ClusterInterceptor` on interceptor references
  tekton/ci/bases/trigger.yaml
  tekton/ci/shared/eventlistener.yaml
  tekton/ci/shared/labels.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/cd/ci-triggers.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/cd/notification-triggers.yaml
  tekton/resources/images/eventlistener.yaml
  tekton/resources/nightly-tests/eventlistener.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
  tekton/resources/release/release-logs/release-logs-triggers.yaml
Labels: kind/bug, lgtm, approved, size/M

#1296 make the name shorter to avoid webhook failure
  tekton/ci/repos/pipeline/template.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1308 Upgraded golangci-lint to 1.50.1 (latest).
  tekton/ci/custom-tasks/pr-commenter/Makefile
  tekton/ci/custom-tasks/pr-commenter/tools/go.mod
  tekton/ci/custom-tasks/pr-status-updater/Makefile
  tekton/ci/custom-tasks/pr-status-updater/tools/go.mod
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/S, kind/cleanup

#1309 Upgraded `test-runner` image to latest.
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/cleanup
