Repository tektoncd/plumbing, pull requests merged in 2022-07, with the labels that each got.

#1104 Deploy interceptors in triggers nightly
  tekton/cronjobs/dogfooding/tekton/triggers-to-robotcat-nightly/cronjob.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1105 Fix the add-pr-body nightly build
  tekton/ci/cluster-interceptors/add-pr-body/tekton/publish.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1107 Fix kind-e2e image by upgrading base image to Go 1.17.x
  pipelinerun-logs/Dockerfile
  tekton/images/coverage/Dockerfile
  tekton/images/kind-e2e/Dockerfile
  tekton/images/kind/Dockerfile
  tekton/images/kubectl/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#1108 Add a build-id cluster interceptor
  tekton/ci/cluster-interceptors/add-pr-body/README.md
  tekton/ci/cluster-interceptors/build-id/README.md
  tekton/ci/cluster-interceptors/build-id/cmd/interceptor/main.go
  tekton/ci/cluster-interceptors/build-id/config/100-serviceaccount.yaml
  tekton/ci/cluster-interceptors/build-id/config/200-interceptor.yaml
  tekton/ci/cluster-interceptors/build-id/config/interceptor-deployment.yaml
  tekton/ci/cluster-interceptors/build-id/go.mod
  tekton/ci/cluster-interceptors/build-id/go.sum
  tekton/ci/cluster-interceptors/build-id/pkg/bid.go
  tekton/ci/cluster-interceptors/build-id/tekton/README.md
  tekton/ci/cluster-interceptors/build-id/tekton/kustomization.yaml
  tekton/ci/cluster-interceptors/build-id/tekton/publish.yaml
  tekton/ci/cluster-interceptors/build-id/tekton/release-pipeline.yaml
Labels: kind/feature, lgtm, approved, size/XXL

#1109 Use the build-id cluster interceptor
  tekton/ci/plumbing/template.yaml
  tekton/ci/shared/bindings.yaml
  tekton/ci/shared/eventlistener.yaml
  tekton/ci/shared/gubernator-metadata.yaml
  tekton/resources/ci/github-gubernator-template.yaml
Labels: kind/feature, lgtm, approved, size/M

#1111 Close some parenthesis left open
  tekton/ci/cluster-interceptors/add-pr-body/tekton/release-pipeline.yaml
  tekton/ci/cluster-interceptors/build-id/tekton/release-pipeline.yaml
  tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml
  tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1113 Bump go version for hub jobs
  prow/config.yaml
Labels: kind/feature, lgtm, approved, size/XS

#1114 Use the deck/spyglass URL to view logs on CI jobs
  tekton/resources/cd/ci-triggers.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/ci/bindings.yaml
  tekton/resources/ci/github-template.yaml
Labels: kind/feature, lgtm, approved, size/M

#1115 Add /usr/local/bin/kind-e2e to test-runner image
  tekton/images/test-runner/Dockerfile
  tekton/images/test-runner/setup-kind.sh
Labels: lgtm, approved, size/L, kind/misc

#1117 Update the buildid cluster interceptor to lower
  tekton/ci/cluster-interceptors/build-id/cmd/interceptor/main.go
  tekton/ci/cluster-interceptors/build-id/config/200-interceptor.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1118 Add optional Pipeline integration-in-Kind Prow job
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1119 Fix command for pull-tekton-pipeline-kind-integration-tests
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1120 Add Pipeline alpha integration Kind-in-Prow job, tweaks to Pipeline job requests
  prow/config.yaml
Labels: lgtm, approved, size/L, kind/misc

#1121 Update kind version in test-runner image
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1125 Add resource requests and limits to chains Prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc

#1126 Update a couple Prow SA roles to match k8s/test-infra's setup
  prow/prow.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1128 Drop node count for Pipeline kind tests from 3 to 2
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1130 Move gitHubRepoUnderscope to the right binding
  tekton/resources/ci/bindings.yaml
Labels: kind/bug, lgtm, approved, size/S

#1129 Add daemonset to Prow cluster to tune sysctl for kind, go back to 3 worker nodes
  docs/prow.md
  prow/config.yaml
  prow/tune-sysctls_daemonset.yaml
Labels: lgtm, approved, size/M, kind/misc

#1132 Remove `/test all` from currently optional Pipeline kind-in-Prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1135 Experiment with requiring that Pipeline kind jobs can't be on the same node
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1140 Switch Pipeline kind jobs to n2-standard-4 nodes
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc

#1141 Replace shortBuildUUID with shortSourceEventId
  tekton/ci/catalog/template.yaml
  tekton/ci/community/template.yaml
  tekton/ci/pipeline/template.yaml
  tekton/ci/plumbing/template.yaml
  tekton/ci/shared/bindings.yaml
  tekton/ci/shared/template.yaml
  tekton/ci/website/template.yaml
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/ci/bindings.yaml
  tekton/resources/ci/github-gubernator-template.yaml
  tekton/resources/ci/github-template.yaml
Labels: kind/bug, lgtm, approved, size/M

#1143 Update legacy syntax in eventlistener.yml
  tekton/resources/nightly-tests/eventlistener.yaml
Labels: lgtm, approved, size/L, ok-to-test, kind/misc

#1142 Streamline CI templates and triggers
  tekton/ci/README.md
  tekton/ci/bases/kustomization.yaml
  tekton/ci/bases/kustomizeconfig/trigger.yaml
  tekton/ci/bases/template.yaml
  tekton/ci/bases/trigger.yaml
  tekton/ci/catalog/kustomization.yaml
  tekton/ci/catalog/trigger.yaml
  tekton/ci/community/kustomization.yaml
  tekton/ci/community/trigger.yaml
  tekton/ci/kustomization.yaml
  tekton/ci/pipeline/kustomization.yaml
  tekton/ci/pipeline/trigger.yaml
  tekton/ci/plumbing/kustomization.yaml
  tekton/ci/plumbing/trigger.yaml
  tekton/ci/repos/catalog/kustomization.yaml
  tekton/ci/repos/catalog/template.yaml
  tekton/ci/repos/catalog/trigger.yaml
  tekton/ci/repos/community/kustomization.yaml
  tekton/ci/repos/community/template.yaml
  tekton/ci/repos/community/trigger.yaml
  tekton/ci/repos/kustomization.yaml
  tekton/ci/repos/pipeline/kustomization.yaml
  tekton/ci/repos/pipeline/template.yaml
  tekton/ci/repos/pipeline/trigger.yaml
  tekton/ci/repos/plumbing/kustomization.yaml
  tekton/ci/repos/plumbing/template.yaml
  tekton/ci/repos/plumbing/trigger.yaml
  tekton/ci/repos/shared/all/kustomization.yaml
  tekton/ci/repos/shared/all/template.yaml
  tekton/ci/repos/shared/all/trigger.yaml
  tekton/ci/repos/shared/doc-reviews/kustomization.yaml
  tekton/ci/repos/shared/doc-reviews/template.yaml
  tekton/ci/repos/shared/doc-reviews/trigger-comment.yaml
  tekton/ci/repos/shared/doc-reviews/trigger-pr.yaml
  tekton/ci/repos/shared/kustomization.yaml
  tekton/ci/repos/website/kustomization.yaml
  tekton/ci/repos/website/template.yaml
  tekton/ci/repos/website/trigger.yaml
  tekton/ci/shared/bindings.yaml
  tekton/ci/shared/kustomization.yaml
  tekton/ci/shared/template.yaml
  tekton/ci/shared/trigger.yaml
  tekton/ci/website/kustomization.yaml
  tekton/ci/website/trigger.yaml
  tekton/mario-bot/mario-image-build-trigger.yaml
Labels: lgtm, approved, size/XXL, kind/misc

#1144 Switch Pipeline to Kind-in-Prow e2e jobs
  prow/config.yaml
Labels: lgtm, approved, size/L, kind/misc

#1146 Fix workingdir->workingDir in various Tasks and Pipelines
  tekton/mario-bot/mario-image-build-trigger.yaml
  tekton/resources/images/single-arch-template.yaml
  tekton/resources/nightly-tests/bastion-p/test_tekton_cli.yaml
  tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-z/cleanup_tekton.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_cli.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
  tekton/resources/nightly-tests/catalog-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/catalog-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
  tekton/resources/release/base/github_release.yaml
  tekton/resources/release/base/test_tekton_release.yaml
Labels: lgtm, approved, size/M, kind/misc

#1152 Add the tekton.dev/pr-number to github notifications
  tekton/resources/ci/github-template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1153 Fix the name of the labels event trigger
  tekton/ci/shared/kustomization.yaml
  tekton/ci/shared/labels-trigger.yaml
  tekton/ci/shared/labels.yaml
Labels: kind/bug, lgtm, approved, size/L

#1154 Check if label.name startswith kind/
  tekton/ci/shared/labels.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1155 Remove last lurking Tasks with apiVersion tekton.dev/v1alpha1
  tekton/ci/shared/common-tasks.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1156 Move images to Golang 1.18.3
  tekton/images/coverage/Dockerfile
  tekton/images/kind-e2e/Dockerfile
  tekton/images/kind/Dockerfile
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/kubectl/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/M, kind/misc

#1158 Update Go 1.17.8 test-runner usages to Go 1.18.3
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1162 Bump tkn to latest release v0.25.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1160 Migrate the configmap CD service to workspaces
  tekton/resources/cd/cleanup-template.yaml
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/folder-template.yaml
Labels: lgtm, approved, size/L, kind/misc

#1161 Cleanup the tekton/resources/release folder
  tekton/resources/cd/eventlistener.yaml
  tekton/resources/nightly-release/overlays/add-pr-body-ci/template.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/template.yaml
  tekton/resources/nightly-release/overlays/add-team-members/template.yaml
  tekton/resources/nightly-release/overlays/cel/template.yaml
  tekton/resources/nightly-release/overlays/chains/template.yaml
  tekton/resources/nightly-release/overlays/cloudevents/template.yaml
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
  tekton/resources/nightly-release/overlays/operator/template.yaml
  tekton/resources/nightly-release/overlays/pipeline-in-pod/template.yaml
  tekton/resources/nightly-release/overlays/pipeline-to-taskrun/template.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
  tekton/resources/nightly-release/overlays/pipelines-in-pipelines/template.yaml
  tekton/resources/nightly-release/overlays/task-loops/template.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
  tekton/resources/nightly-release/overlays/wait-task/template.yaml
  tekton/resources/release/README.md
  tekton/resources/release/base/install_and_test_tekton_release.yaml
  tekton/resources/release/base/kustomization.yaml
  tekton/resources/release/base/nightly-release-logs-trigger.yaml
  tekton/resources/release/base/save-release-logs.yaml
  tekton/resources/release/base/test_tekton_release.yaml
  tekton/resources/release/kustomization.yaml
  tekton/resources/release/release-logs/kustomization.yaml
  tekton/resources/release/release-logs/rbac.yaml
  tekton/resources/release/release-logs/release-logs-triggers.yaml
  tekton/resources/release/release-logs/save-release-logs.yaml
Labels: lgtm, approved, size/XXL, kind/misc

#1163 Migrate the helm template CD service to workspaces
  tekton/resources/cd/helm-template.yaml
Labels: lgtm, approved, size/L, kind/misc

#1167 Remove --cluster-suffix from kind-e2e calls
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1166 Set requests/limits on post-tekton-pipeline-go-coverage
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1164 Migrate install Tekton release CD service to workspaces
  robocat/README.md
  tekton/cd/README.md
  tekton/images/koparse/koparse/test_release.yaml
  tekton/resources/cd/clusters.yaml
  tekton/resources/cd/helm-template.yaml
  tekton/resources/cd/install-tekton-release.yaml
  tekton/resources/cd/kustomization.yaml
  tekton/resources/cd/tekton-template.yaml
  tekton/resources/nightly-release/base/kustomizeconfig/pipeline.yaml
  tekton/resources/release/README.md
  tekton/resources/release/base/install_tekton_release.yaml
  tekton/resources/release/base/kustomization.yaml
Labels: size/XL, lgtm, approved, kind/misc

#1169 Fix the label check
  tekton/ci/shared/labels.yaml
Labels: lgtm, approved, size/S, kind/misc

#1170 kaniko4ci should handle changes in subdirectories for images
  tekton/ci/jobs/tekton-image-build.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1171 Enable pipeline feature flags in robocat
  tekton/cd/pipeline/overlays/robocat/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1172 Remove clusters.yaml from list of resources
  tekton/resources/cd/kustomization.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1173 Add ahmetb-gen-crd-api-reference-docs to Prow config
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc
