Repository tektoncd/plumbing, pull requests merged in 2022-05, with the labels that each got.

#1024 Updates the context path for catlin nightly cronjob
  tekton/cronjobs/dogfooding/images/catlin-nightly/cronjob.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1078 Add release automation for pipeline-in-pod project
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/README.md
  tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline-in-pod/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline-in-pod/template.yaml
  tekton/resources/nightly-release/overlays/pipeline-in-pod/trigger.yaml
Labels: lgtm, approved, size/M, kind/misc

#1079 tkn-nightly: add linux/arm64 to platforms to build
  tekton/cronjobs/dogfooding/images/tkn-nightly/cronjob.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1081 Update ko to 0.11.2 in the ko images
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#1080 Support using podman in kind script
  hack/tekton_in_kind.sh
Labels: kind/feature, lgtm, approved, size/S

#1083 label_sync: add a grooming label
  label_sync/labels.yaml
Labels: lgtm, approved, size/S, kind/misc
