Repository tektoncd/plumbing, pull requests merged in 2023-02, with the labels that each got.

#1311 Bump tkn to latest release v0.29.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1278 Add docker-in-docker image in sidecar to fix CI issue for ppc64le
  tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml
Labels: lgtm, approved, size/M, ok-to-test, kind/misc

#1256 Add beta integration test for V1 release
  gubernator/config.yaml
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1335 Bump tkn to v0.29.1
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1336 Revert "Migrate Triggers e2e test to kind"
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/M

#1333 Configure the git resolver with the GitHub API token
  tekton/cd/pipeline/overlays/dogfooding/git-resolver-config.yaml
  tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
Labels: lgtm, approved, size/S, kind/misc

#1339 Remove `embedded-status` feature flag
  prow/config.yaml
  tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1334 Add golang verified catalog build test infra
  tekton/ci/jobs/tekton-catalog-catlin-lint.yaml
  tekton/ci/repos/catalog/base/kustomization.yaml
  tekton/ci/repos/catalog/base/template.yaml
  tekton/ci/repos/catalog/community-catalog/kustomization.yaml
  tekton/ci/repos/catalog/community-catalog/template.yaml
  tekton/ci/repos/catalog/community-catalog/trigger.yaml
  tekton/ci/repos/catalog/verified-catalogs/base/kustomization.yaml
  tekton/ci/repos/catalog/verified-catalogs/base/template.yaml
  tekton/ci/repos/catalog/verified-catalogs/golang/kustomization.yaml
  tekton/ci/repos/catalog/verified-catalogs/golang/trigger.yaml
  tekton/ci/shared/eventlistener.yaml
Labels: kind/feature, lgtm, approved, size/M

#1244 Fix publish.yaml for pr-commenter
  tekton/ci/custom-tasks/pr-commenter/tekton/publish.yaml
Labels: lgtm, approved, size/S, kind/misc

#1342 Patch missing kustomization files for verified catalog build tests
  tekton/ci/repos/catalog/kustomization.yaml
  tekton/ci/repos/catalog/verified-catalogs/kustomization.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1343 Fix extra open parenthesis in the event listener
  tekton/ci/shared/eventlistener.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1345 Add "-post-comment" filter to "ci-job-triggers" trigger group
  tekton/resources/cd/eventlistener.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1348 Switch Kind Cluster to v1.24.X for Beta Integration Test
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1349 Add resource deployment and Github Check update documentation
  tekton/cd/README.md
  tekton/ci/README.md
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton/README.md
Labels: lgtm, approved, size/S, kind/documentation

#1350 Clean up catlin-linter and diff-task-job usage
  tekton/ci/jobs/tekton-catalog-catlin-lint.yaml
  tekton/ci/repos/catalog/base/template.yaml
  tekton/ci/repos/catalog/community-catalog/template.yaml
  tekton/ci/repos/catalog/verified-catalogs/base/template.yaml
Labels: lgtm, approved, size/M, kind/cleanup

#1352 Bump to go 1.19 for coverage Dockerifle
  tekton/images/coverage/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1365 Bump go to 1.19 for tkn Dockerfile…
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1362 Bump go to 1.19 for kubectl Dockerfile…
  tekton/images/kubectl/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1363 Bump alpine to 3.16 on skopeo Dockerfile
  tekton/images/skopeo/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1364 Bump go to 1.19 for test-runner Dockerfile…
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#1358 Bump go to 1.19 for ko Dockerfile…
  tekton/images/ko/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1355 Update the hub image content
  tekton/images/hub/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1353 Update alpine-git-nonroot to v2.36.3.
  tekton/images/alpine-git-nonroot/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1354 Pin buildx-gcloud image with Digest
  tekton/images/buildx-gcloud/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1356 Bump go to 1.19 for kind Dockerfile…
  tekton/images/kind/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1357 Bump go to 1.19 for kind-e2e Dockerfile…
  tekton/images/kind-e2e/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1359 Bump go to 1.19 for ko-gcloud Dockerfile…
  tekton/images/ko-gcloud/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1360 Bump python to 3.11 for koparse
  tekton/images/koparse/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1361 Pin openssh-server Dockerfile with digest
  tekton/images/openssh-server/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1368 This add a dependbot configuration for Dockerfiles
  .github/dependabot.yml
Labels: lgtm, approved, size/XS, kind/misc

#1369 Bump prow test-runner.
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1372 Enable release-note and cherrypicker for results
  prow/plugins.yaml
Labels: lgtm, approved, size/XS, kind/misc
