Repository tektoncd/plumbing, pull requests merged in 2023-05, with the labels that each got.

#1392 skip pipelineresource tests
  tekton/resources/nightly-tests/bastion-z/test_tekton_cli.yaml
Labels: lgtm, approved, size/XS

#1401 Bump tkn to v0.31.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1399 fix pipelines ci failures due to push permissions
  tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
Labels: lgtm, approved, size/S, kind/misc

#1404 Pin test-runner image for pipelines integration tests
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1376 dependabot: Add go modules + labels.
  .github/dependabot.yml
Labels: lgtm, approved, size/L, kind/misc

#1406 Update integration test runner images to go 1.19
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1403 Provide workspace optional flag for CI tests
  tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1438 Add individual dependabot entries for dockerfile dirs.
  .github/dependabot.yml
Labels: lgtm, approved, size/L, kind/cleanup
