Repository tektoncd/plumbing, pull requests merged in 2023-10, with the labels that each got.

#1636 Updates test-runner image for Tekton Hub
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1649 Update test-runner image for Dashboard jobs to use go 1.20
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1652 Bump tkn to v0.32.1 in images
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1635 Update Go to 1.20.10
  tekton/images/ko/Dockerfile
Labels: lgtm, approved, size/XS, kind/security

#1653 Bump tkn to v0.32.2
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS
