Repository tektoncd/plumbing, pull requests merged in 2023-11, with the labels that each got.

#1670 dependabot: group dependency updates
  .github/dependabot.yml
Labels: lgtm, approved, size/L, kind/misc

#1706 Remove lifecycle plugin from tektoncd org
  prow/plugins.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1707 update test-runner image for operator to use go 1.20
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1718 Effectively disable lifecycle management
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1720 Bump tkn to v0.33.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1721 Update ko and kubectl images
  tekton/images/ko/Dockerfile
  tekton/images/kubectl/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1719 Updated images-build task to utilize matrix as input
  tekton/ci/jobs/tekton-image-build.yaml
Labels: lgtm, approved, size/XS, ok-to-test, kind/misc
