Repository tektoncd/plumbing, pull requests merged in 2023-09, with the labels that each got.

#1581 Use Ubuntu instead of debian as base image
  tekton/images/test-runner/Dockerfile
Labels: kind/bug, lgtm, approved, size/S

#1582 Use latest test-runner for CLI and Hub
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc

#1584 Use 1.20 go image for tektoncd/chains
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1583 Bump tkn to `v0.32.0`
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1592 Ignore deprecated tasks while catlin validate
  tekton/ci/jobs/tekton-catalog-catlin-lint.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1594 Bump k8s version in operator jobs
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1595 Bump test-runner image
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1596 Use kind to run e2e CI on catalog
  prow/config.yaml
Labels: kind/feature, lgtm, approved, size/M

#1597 Point to correct e2e tests script for catalog
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1598 Remove pod affinity from catalog e2e
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/S

#1600 Fix e2e runner image for catalog
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1611 Update ko image to go 1.20
  tekton/images/ko/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1601 Use Kind cluster while running nightly catalog e2e
  prow/config.yaml
Labels: kind/feature, lgtm, approved, size/M

#1613 Fix Rerun and Trigger Commands
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc

#1623 Increase the pipeline release timeout
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: lgtm, approved, size/XS, kind/misc
