Repository tektoncd/plumbing, pull requests merged in 2023-07, with the labels that each got.

#1503 Fix typos in deploy script readme
  scripts/README.md
Labels: lgtm, approved, size/XS, kind/documentation

#1511 Adapt the deployment logic to chains
  robocat/cadmin/200-rbac.yaml
  scripts/deploy-release.sh
  tekton/resources/cd/install-tekton-release.yaml
Labels: lgtm, approved, size/S, kind/misc

#1513 Add pipelinerun settings for chains v0.16
  tekton/cd/chains/overlays/dogfooding/chains-config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1507 Cleanup supported k8s version in test-runner
  tekton/images/test-runner/Dockerfile
  tekton/images/test-runner/setup-kind.sh
Labels: lgtm, approved, size/M, kind/cleanup

#1520 Use kubernetes 1.25 on kind for pipeline
  prow/config.yaml
Labels: lgtm, approved, size/XS

#1521 Update test-runner image in prow config
  prow/config.yaml
Labels: kind/bug, lgtm, approved, size/S
