Repository tektoncd/plumbing, pull requests merged in 2023-08, with the labels that each got.

#1528 Bump tkn to v0.31.2
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1529 Drop legacy unused resource which breaks deployment
  tekton/resources/nightly-release/kustomization.yaml
  tekton/resources/nightly-release/tasks.yaml
Labels: kind/bug, lgtm, approved, size/M

#1561 Bump golang to 1.20 in test-runner
  tekton/images/test-runner/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1562 Update to k8s 1.25 for Dashboard integration tests
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1564 Bump hub jobs to go 1.20
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1563 Update test-runner image used for Dashboard jobs
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc
