Repository tektoncd/plumbing, pull requests merged in 2024-09, with the labels that each got.

#1954 Add example testsuite for tekton-pipeline CI job for ppc64le
  tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml
Labels: lgtm, approved, size/M, ok-to-test, kind/misc

#2067 tekton/images: update kubectl and kustomize versions
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/kubectl/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#2158 Move the pipeline nightly build to ghcr
  tekton/cronjobs/bases/release/trigger-with-uuid.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-nightly/cronjob.yaml
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/nightly-release/bindings.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: lgtm, approved, size/M, kind/misc

#2177 Fix type in pipeline release run
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: kind/bug, lgtm, approved, size/XS

#2176 Update tkn to 0.38.1
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#2178 Remove the package path from pipeline images
  tekton/cronjobs/dogfooding/releases/pipeline-nightly/cronjob.yaml
  tekton/resources/nightly-release/overlays/pipeline/template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2179 Resore default values for nightlies
  tekton/cronjobs/bases/release/trigger-with-uuid.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2180 Remove empty cronjobs folder from robocat
  tekton/cronjobs/robocat/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2189 Add koparse support for no-preserve-path
  tekton/images/koparse/koparse/koparse.py
  tekton/images/koparse/koparse/test_koparse.py
  tekton/images/koparse/koparse/test_release_no_preserve_path.yaml
  tekton/resources/images/single-arch-template.yaml
Labels: kind/feature, size/XL, lgtm, approved

#2190 Fix the sha of the python image in koparse
  tekton/images/koparse/Dockerfile
Labels: kind/bug, lgtm, approved, size/XS

#2192 kaniko needs a force option in CI jobs
  tekton/ci/jobs/tekton-image-build.yaml
Labels: kind/bug, lgtm, approved, size/XS

#2194 Fix bugs in the new version of koparse
  tekton/images/koparse/koparse/koparse.py
Labels: lgtm, approved, size/S, kind/misc

#2195 Add AlanGreene to the approvers
  OWNERS
Labels: lgtm, approved, size/XS, kind/misc

#2196 Fix param order in koparse backwards_compatible_params
  tekton/images/koparse/koparse/koparse.py
Labels: kind/bug, lgtm, approved, size/XS

#2198 Revert changes to single arch template
  tekton/resources/images/single-arch-template.yaml
Labels: kind/bug, lgtm, approved, size/M

#2202 Move the Dashboard nightly image to GHCR
  tekton/cronjobs/dogfooding/releases/dashboard-nightly/cronjob.yaml
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
Labels: lgtm, approved, size/S, kind/misc

#2203 Pin images used in the add-pr-body interceptor release pipeline
  tekton/ci/cluster-interceptors/add-pr-body/tekton/publish.yaml
  tekton/ci/cluster-interceptors/add-pr-body/tekton/release-pipeline.yaml
  tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml
Labels: lgtm, approved, size/S, kind/misc

#2205 Pin images used in the custom tasks release pipelines
  tekton/ci/custom-tasks/pr-commenter/tekton/publish.yaml
  tekton/ci/custom-tasks/pr-commenter/tekton/release-pipeline.yaml
  tekton/ci/custom-tasks/pr-status-updater/tekton/publish.yaml
  tekton/ci/custom-tasks/pr-status-updater/tekton/release-pipeline.yaml
Labels: lgtm, approved, size/S, kind/misc

#2193 Enable CEL in when expressions
  tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2206 Switch Triggers nightlies to ghcr.io
  tekton/cronjobs/dogfooding/releases/triggers-nightly/cronjob.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: lgtm, approved, size/S, kind/misc

#2207 Fix a typo in the triggers release workspace
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: kind/bug, lgtm, approved, size/XS

#2209 Fix path of Triggers images published to ghcr.io
  tekton/cronjobs/dogfooding/releases/triggers-nightly/cronjob.yaml
  tekton/resources/nightly-release/overlays/triggers/template.yaml
Labels: lgtm, approved, size/XS, kind/misc
