Repository tektoncd/plumbing, pull requests merged in 2024-07, with the labels that each got.

#2044 Enable feature flags for running tests on s390x/ppc64le platform
  tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2059 Update test-runner image to the latest…
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#2063 Fix invalid image names in prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#2066 tekton/images: fetch `ko` from upstream image.
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#2064 tekton/images: remove openssh-server…
  tekton/cronjobs/dogfooding/images/kustomization.yaml
  tekton/cronjobs/dogfooding/images/openssh-server-nightly/README.md
  tekton/cronjobs/dogfooding/images/openssh-server-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/images/openssh-server-nightly/kustomization.yaml
  tekton/images/openssh-server/Dockerfile
Labels: lgtm, approved, size/M, kind/misc

#2101 Do not fail on missing dockerfile
  tekton/ci/jobs/tekton-image-build.yaml
Labels: kind/bug, lgtm, approved, size/XS
