Repository tektoncd/plumbing, pull requests merged in 2024-05, with the labels that each got.

#1953 Bump Hub build, test and integration CI image to go 1.22
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1956 Update the peribolos token
  docs/dogfooding.md
  tekton/ci/jobs/tekton-golang-coverage.yaml
  tekton/resources/org-permissions/peribolos-trigger.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1957 Bump tkn to v0.37.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1970 Fix peribolos secret in the tekton-cd el
  tekton/resources/cd/peribolos-template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1984 Update kind version of projects to 1.28.x
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc

#1986 Revert "Update kind version of projects to 1.28.x"
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc

#1988 Update `setup-kind.sh` scripts…
  tekton/images/kind-e2e/setup-kind.sh
  tekton/images/test-runner/setup-kind.sh
Labels: lgtm, approved, size/M, kind/misc

#1987 Update kind version of projects to 1.28.x…
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc
