Repository tektoncd/plumbing, pull requests merged in 2024-12, with the labels that each got.

#2326 feat: Update credentials for multi arch images
  tekton/resources/images/docker-multi-arch-template.yaml
Labels: kind/feature, lgtm, approved, size/S, ok-to-test

#2327 feat: Update credentials for Ko Multi-Arch Images
  tekton/resources/images/ko-multi-arch-template.yaml
Labels: kind/feature, lgtm, approved, size/S, ok-to-test

#2300 Sunset experimental: disable all experimental cronjobs and builds
  prow/config.yaml
  tekton/cronjobs/dogfooding/releases/cel-nightly/README.md
  tekton/cronjobs/dogfooding/releases/cel-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/cel-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/cloudevents-nightly/README.md
  tekton/cronjobs/dogfooding/releases/cloudevents-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/cloudevents-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/concurrency-nightly/README.md
  tekton/cronjobs/dogfooding/releases/concurrency-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/concurrency-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/README.md
  tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-to-taskrun-nightly/README.md
  tekton/cronjobs/dogfooding/releases/pipeline-to-taskrun-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pipeline-to-taskrun-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/pipelines-in-pipelines-nightly/README.md
  tekton/cronjobs/dogfooding/releases/pipelines-in-pipelines-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pipelines-in-pipelines-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/task-loops-nightly/README.md
  tekton/cronjobs/dogfooding/releases/task-loops-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/task-loops-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/wait-task-nightly/README.md
  tekton/cronjobs/dogfooding/releases/wait-task-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/wait-task-nightly/kustomization.yaml
  tekton/cronjobs/dogfooding/releases/workflows-nightly/README.md
  tekton/cronjobs/dogfooding/releases/workflows-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/workflows-nightly/kustomization.yaml
  tekton/resources/cd/install-tekton-release.yaml
  tekton/resources/nightly-release/overlays/cel/kustomization.yaml
  tekton/resources/nightly-release/overlays/cel/template.yaml
  tekton/resources/nightly-release/overlays/cel/trigger.yaml
  tekton/resources/nightly-release/overlays/cloudevents/kustomization.yaml
  tekton/resources/nightly-release/overlays/cloudevents/template.yaml
  tekton/resources/nightly-release/overlays/cloudevents/trigger.yaml
  tekton/resources/nightly-release/overlays/concurrency/kustomization.yaml
  tekton/resources/nightly-release/overlays/concurrency/template.yaml
  tekton/resources/nightly-release/overlays/concurrency/trigger.yaml
  tekton/resources/nightly-release/overlays/pipeline-in-pod/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline-in-pod/template.yaml
  tekton/resources/nightly-release/overlays/pipeline-in-pod/trigger.yaml
  tekton/resources/nightly-release/overlays/pipeline-to-taskrun/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline-to-taskrun/template.yaml
  tekton/resources/nightly-release/overlays/pipeline-to-taskrun/trigger.yaml
  tekton/resources/nightly-release/overlays/pipelines-in-pipelines/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipelines-in-pipelines/template.yaml
  tekton/resources/nightly-release/overlays/pipelines-in-pipelines/trigger.yaml
  tekton/resources/nightly-release/overlays/task-loops/kustomization.yaml
  tekton/resources/nightly-release/overlays/task-loops/template.yaml
  tekton/resources/nightly-release/overlays/task-loops/trigger.yaml
  tekton/resources/nightly-release/overlays/wait-task/kustomization.yaml
  tekton/resources/nightly-release/overlays/wait-task/template.yaml
  tekton/resources/nightly-release/overlays/wait-task/trigger.yaml
  tekton/resources/nightly-release/overlays/workflows/kustomization.yaml
  tekton/resources/nightly-release/overlays/workflows/template.yaml
  tekton/resources/nightly-release/overlays/workflows/trigger.yaml
Labels: size/XL, lgtm, approved, kind/cleanup

#2329 Remove references to deleted experimental resources
  tekton/cronjobs/dogfooding/releases/kustomization.yaml
  tekton/resources/nightly-release/kustomization.yaml
Labels: lgtm, approved, size/S, kind/misc

#2332 Update tkn to 0.39.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#2330 Reusable actions to restest GitHub actions
  .github/actions/_chatops_retest.yml
  .github/actions/_slash.yml
Labels: kind/feature, lgtm, approved, size/L

#2333 Set required status checks for pipeline
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2335 Bump test runner image for Tekton Hub
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2334 Move reusable workflows to correct location
  .github/workflows/_chatops_retest.yml
  .github/workflows/_slash.yml
Labels: lgtm, approved, size/XS, kind/misc

#2337 Update operator nightly builds for ghcr.io
  tekton/cronjobs/dogfooding/releases/operator-nightly/cronjob.yaml
  tekton/resources/nightly-release/overlays/operator/template.yaml
Labels: lgtm, approved, size/S, kind/misc

#2336 Add a taskrun to copy images from gcr.io to ghcr.io
  tekton/resources/images/copy-all-skopeo.yaml
Labels: lgtm, approved, size/M, kind/misc

#2342 Rework plumbing nightlies
  tekton/catalog/pipelines/release.yaml
  tekton/catalog/tasks/publish.yaml
  tekton/ci/cluster-interceptors/add-pr-body/tekton/README.md
  tekton/ci/cluster-interceptors/add-pr-body/tekton/kustomization.yaml
  tekton/ci/cluster-interceptors/add-pr-body/tekton/publish.yaml
  tekton/ci/cluster-interceptors/add-pr-body/tekton/release-pipeline.yaml
  tekton/ci/custom-tasks/pr-commenter/tekton/README.md
  tekton/ci/custom-tasks/pr-commenter/tekton/kustomization.yaml
  tekton/ci/custom-tasks/pr-commenter/tekton/publish.yaml
  tekton/ci/custom-tasks/pr-status-updater/tekton/README.md
  tekton/ci/custom-tasks/pr-status-updater/tekton/kustomization.yaml
  tekton/ci/custom-tasks/pr-status-updater/tekton/release-pipeline.yaml
  tekton/ci/interceptors/add-pr-body/tekton/README.md
  tekton/ci/interceptors/add-pr-body/tekton/kustomization.yaml
  tekton/ci/interceptors/add-pr-body/tekton/publish.yaml
  tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml
  tekton/ci/interceptors/add-team-members/tekton/README.md
  tekton/ci/interceptors/add-team-members/tekton/kustomization.yaml
  tekton/ci/interceptors/add-team-members/tekton/publish.yaml
  tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml
  tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/README.md
  tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/add-pr-body-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/add-team-members-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pr-commenter-nightly/cronjob.yaml
  tekton/cronjobs/dogfooding/releases/pr-status-updater-nightly/cronjob.yaml
  tekton/resources/nightly-release/overlays/add-pr-body-ci/template.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/template.yaml
  tekton/resources/nightly-release/overlays/add-team-members/template.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/template.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/template.yaml
Labels: lgtm, approved, size/XXL, kind/misc

#2343 Fix kustomize for local nightlies
  tekton/resources/nightly-release/overlays/add-pr-body-ci/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-team-members/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2344 Fix unit tests - update go version
  pipelinerun-logs/go.mod
  pipelinerun-logs/go.sum
  tekton/ci/jobs/tekton-golang-tests.yaml
Labels: lgtm, approved, size/XXL, kind/misc

#2345 Fix missing release bucket
  tekton/resources/nightly-release/overlays/add-pr-body-ci/template.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/template.yaml
  tekton/resources/nightly-release/overlays/add-team-members/template.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/template.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/template.yaml
Labels: lgtm, approved, size/S, kind/misc

#2346 god mod tiny for github interceptor
  tekton/ci/interceptors/github/go.mod
  tekton/ci/interceptors/github/go.sum
Labels: lgtm, approved, size/XXL, kind/misc
