Repository tektoncd/plumbing, pull requests merged in 2024-02, with the labels that each got.

#1799 Bump tkn to v0.35.0
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/feature, lgtm, approved, size/XS

#1801 Add cherrypicker plugin to help with Dashboard patch releases
  prow/plugins.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1798 Update k8s version used for Dashboard integration tests
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1817 Bump tkn to v0.35.1
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/bug, lgtm, approved, size/XS

#1803 Add Prow setup for feature flag tests
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#1797 ppc64le job config modified with JFrog registry
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/cli-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/operator-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/pipeline-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/triggers-nightly-test/cronjob.yaml
Labels: lgtm, approved, size/S, ok-to-test, kind/misc

#1820 Fix Results Watcher deployment
  tekton/cd/results/overlays/dogfooding/watcher.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1802 Update Dashboard nightly release to use v1 PipelineRun API
  tekton/resources/nightly-release/overlays/dashboard/template.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1819 Remove unused file causing Pipelines nightly deploy to fail
  tekton/cd/pipeline/overlays/robocat/config-artifact-bucket.yaml
  tekton/cd/pipeline/overlays/robocat/kustomization.yaml
Labels: lgtm, approved, size/S, kind/misc

#1822 Add extra roles to deployer sa for resolvers
  robocat/cadmin/200-rbac.yaml
Labels: lgtm, approved, size/M, kind/misc

#1823 Fix first-time configmap-template script
  tekton/resources/cd/configmap-template.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1824 Isolate new env nightly feature flag test
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1834 Fix invalid metadata.description
  tekton/ci/jobs/tekton-github-tasks-completed.yaml
  tekton/ci/jobs/tekton-kind-label.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1818 Add tektoncd/actions to tide
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1835 Dogfood StepActions Setup
  tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1836 Cronjob timings and timeout modified for ppc64le jobs
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/cli-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/operator-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/pipeline-nightly-test/cronjob.yaml
  tekton/cronjobs/dogfooding/nightly-tests/ppc64le/triggers-nightly-test/cronjob.yaml
  tekton/resources/nightly-tests/catalog-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/cli-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-ppc64le-template.yaml
Labels: lgtm, approved, size/S, ok-to-test

#1837 Make sure the folder deployment succeeds in case of noop
  tekton/resources/cd/folder-template.yaml
Labels: kind/bug, lgtm, approved, size/S

#1838 Enable OCI bundles use in dogfooding
  tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
Labels: lgtm, approved, size/XS, kind/misc

#1821 doc(hack): add available argument for the script
  hack/README.md
Labels: lgtm, approved, size/XS, kind/documentation, ok-to-test

#1614 tektn/images/test-runner: remove old comment…
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1717 Update alpine in the hub oci image
  tekton/images/hub/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#1732 Update ko version in kind images
  tekton/images/kind-e2e/Dockerfile
  tekton/images/kind/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#1849 Dogfood StepActions via go-coverage CI pipeline
  tekton/ci/jobs/tekton-golang-coverage.yaml
  tekton/ci/kustomization.yaml
  tekton/ci/stepactions/gcs-upload.yaml
  tekton/ci/stepactions/git-batch-merge.yaml
  tekton/ci/stepactions/kustomization.yaml
Labels: lgtm, approved, size/L, kind/misc

#1850 images/test-runner: update a bunch of tools
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc
