Repository tektoncd/plumbing, pull requests merged in 2025-07, with the labels that each got.

#2689 .github/workflows: add a "build" image workflow
  .github/workflows/images.yaml
Labels: lgtm, approved, size/M, kind/misc

#2692 Create a CI workflow for plumbing
  .github/workflows/ci.yaml
  bots/mariobot/go.mod
  tekton/ci/custom-tasks/pr-commenter/.golangci.yml
  tekton/ci/custom-tasks/pr-status-updater/.golangci.yml
  tekton/ci/repos/plumbing/template.yaml
Labels: lgtm, approved, size/L, kind/misc

#2690 Add an alpine based `tini-git` image
  tekton/images/tini-git/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#2708 tini-git: add USER by default
  tekton/images/tini-git/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#2510 Remove tektoncd/cli prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/L, kind/misc

#2715 ci: update branch protection status checks for tektoncd/cli
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc
