Repository tektoncd/plumbing, pull requests merged in 2025-01, with the labels that each got.

#2341 Update go 1.23 in our images
  tekton/images/coverage/Dockerfile
  tekton/images/kind-e2e/Dockerfile
  tekton/images/kind/Dockerfile
  tekton/images/ko-gcloud/Dockerfile
  tekton/images/ko/Dockerfile
  tekton/images/kubectl/Dockerfile
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/S, kind/misc

#2347 prow: update test-runner images everywhere with latest
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#2348 Fix the publish.yaml from the catalog
  .gitignore
  tekton/catalog/tasks/publish.yaml
Labels: lgtm, approved, size/S, kind/misc

#2349 Fix koparse version in catalog release
  tekton/catalog/tasks/publish.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2350 Some more fixes to catalog/publish
  .gitignore
  tekton/catalog/tasks/publish.yaml
Labels: lgtm, approved, size/S, kind/misc

#2351 Fixes to koparse params
  tekton/catalog/tasks/publish.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2354 go mod tidy on add-pr-body ci
  tekton/ci/cluster-interceptors/add-pr-body/go.mod
Labels: lgtm, approved, size/XS, kind/misc

#2352 Remove Dashboard PR prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/L, kind/misc

#2390 Remove chains prow-based integration tests
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#2392 tekton/images: fix digest ensure we use the index image digest…
  tekton/images/coverage/Dockerfile
  tekton/images/test-runner/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#2407 Remove retries field from Tekton pipeline templates for ppc64le
  tekton/resources/nightly-tests/cli-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-ppc64le-template.yaml
Labels: lgtm, approved, size/XS, kind/cleanup, ok-to-test

#2409 Update test-runner image with latest
  prow/config.yaml
Labels: lgtm, approved, size/M, kind/misc

#2389 Add lint github workflow as required for pipeline
  prow/config.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2419 Bump to tkn v0.39.1
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: kind/bug, lgtm, approved, size/XS
