Repository tektoncd/plumbing, pull requests merged in 2025-03, with the labels that each got.

#2477 Update tkn to 0.40.0
  go.mod
  tekton/images/test-runner/Dockerfile
  tekton/images/tkn/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#2509 Remove most tektoncd/operator prow jobs
  prow/config.yaml
Labels: lgtm, approved, size/L, kind/misc

#2520 prow: add required checks for operator
  prow/config.yaml
Labels: lgtm, approved, size/S, kind/misc

#2478 Remove retries from s390x nightly tests
  tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
  tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Labels: lgtm, approved, size/S, kind/misc

#2521 Update ko-gcloud to go 1.24
  tekton/images/ko-gcloud/Dockerfile
Labels: lgtm, approved, size/XS, kind/misc

#2487 Fix failing kind cluster start and update docs
  CONTRIBUTING.md
  DEVELOPMENT.md
  hack/README.md
  hack/tekton_in_kind.sh
Labels: lgtm, approved, size/L, kind/documentation, ok-to-test

#2537 Fix subpath capitalisation
  tekton/catalog/pipelines/release.yaml
Labels: kind/bug, lgtm, approved, size/S

#2339 Remove references to gcr.io/tekton*
  bots/buildcaptain/README.md
  bots/mariobot/cmd/mario/main.go
  bots/mariobot/config/mario.yaml
  cmd/combine/README.md
  scripts/e2e-tests.sh
  scripts/library.sh
  tekton/ci/cluster-interceptors/add-pr-body/README.md
  tekton/ci/cluster-interceptors/build-id/README.md
  tekton/ci/interceptors/add-pr-body/README.md
  tekton/ci/interceptors/add-team-members/README.md
  tekton/ci/jobs/tekton-image-build.yaml
  tekton/ci/repos/plumbing/template.yaml
  tekton/ci/stepactions/git-batch-merge.yaml
  tekton/cronjobs/README.md
  tekton/cronjobs/bases/image-build/trigger-image-build.yaml
  tekton/cronjobs/dogfooding/catalog/tekton-upstream/README.md
  tekton/images/koparse/koparse/koparse.py
  tekton/resources/cd/cleanup-template.yaml
  tekton/resources/cd/configmap-template.yaml
  tekton/resources/cd/folder-template.yaml
  tekton/resources/cd/helm-template.yaml
  tekton/resources/nightly-release/README.md
  tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml
  tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
  tekton/resources/release/base/github_release.yaml
Labels: lgtm, approved, size/M, kind/misc

#2538 Go mod tidy on interceptors
  tekton/ci/cluster-interceptors/add-pr-body/go.mod
  tekton/ci/cluster-interceptors/build-id/go.mod
  tekton/ci/cluster-interceptors/build-id/go.sum
  tekton/ci/interceptors/add-pr-body/go.mod
  tekton/ci/interceptors/add-team-members/go.mod
  tekton/ci/interceptors/github/go.mod
Labels: lgtm, approved, size/M, kind/misc
