Repository tektoncd/plumbing, pull requests merged in 2025-08, with the labels that each got.

#2728 .github/workflows: build images for multiple architectures
  .github/workflows/images.yaml
  tekton/images/generate-matrix.py
Labels: lgtm, approved, size/L, kind/misc

#2756 Replace deprecated Dashboard extension displayname field
  tekton/cd/dashboard/overlays/dogfooding/extensions.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2777 Fix the dashboard ingress in OCI
  tekton/cd/dashboard/overlays/oci-ci-cd/ingress.yaml
Labels: lgtm, approved, kind/misc

#2789 Add nightly cronjobs and OCI
  tekton/cronjobs/nightly_oci/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/add-pr-body-ci-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/add-pr-body-ci-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/add-pr-body-ci-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/add-pr-body-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/add-pr-body-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/add-pr-body-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/add-team-members-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/add-team-members-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/add-team-members-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/chains-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/chains-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/chains-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/dashboard-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/dashboard-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/dashboard-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/nextcron.txt
  tekton/cronjobs/nightly_oci/releases/operator-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/operator-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/operator-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/pr-commenter-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/pr-commenter-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/pr-commenter-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/pr-status-updater-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/pr-status-updater-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/pr-status-updater-nightly/kustomization.yaml
  tekton/cronjobs/nightly_oci/releases/triggers-nightly/README.md
  tekton/cronjobs/nightly_oci/releases/triggers-nightly/cronjob.yaml
  tekton/cronjobs/nightly_oci/releases/triggers-nightly/kustomization.yaml
Labels: lgtm, approved, size/L, kind/misc

#2790 Convert nightly triggers to v1beta1
  tekton/resources/nightly-release/base/template.yaml
  tekton/resources/nightly-release/base/trigger.yaml
  tekton/resources/nightly-release/eventlistener.yaml
  tekton/resources/nightly-release/overlays/add-pr-body-ci/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-pr-body-ci/trigger.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-pr-body/trigger.yaml
  tekton/resources/nightly-release/overlays/add-team-members/kustomization.yaml
  tekton/resources/nightly-release/overlays/add-team-members/trigger.yaml
  tekton/resources/nightly-release/overlays/chains/kustomization.yaml
  tekton/resources/nightly-release/overlays/chains/trigger.yaml
  tekton/resources/nightly-release/overlays/dashboard/kustomization.yaml
  tekton/resources/nightly-release/overlays/dashboard/trigger.yaml
  tekton/resources/nightly-release/overlays/operator/kustomization.yaml
  tekton/resources/nightly-release/overlays/operator/trigger.yaml
  tekton/resources/nightly-release/overlays/pipeline/kustomization.yaml
  tekton/resources/nightly-release/overlays/pipeline/trigger.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-commenter/trigger.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/kustomization.yaml
  tekton/resources/nightly-release/overlays/pr-status-updater/trigger.yaml
  tekton/resources/nightly-release/overlays/triggers/kustomization.yaml
  tekton/resources/nightly-release/overlays/triggers/trigger.yaml
Labels: lgtm, approved, size/L, kind/misc

#2791 Configure pod scheduling in OCI
  tekton/cd/pipeline/overlays/oci-ci-cd/config-defaults.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2793 Remove all Azure specific overlays
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-azure/README.md
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-azure/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-azure/kustomization.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-releases-azure/README.md
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-releases-azure/cronjob.yaml
  tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-releases-azure/kustomization.yaml
  tekton/cronjobs/releases_azure/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/add-pr-body-ci-nightly/README.md
  tekton/cronjobs/releases_azure/releases/add-pr-body-ci-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/add-pr-body-ci-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/add-pr-body-nightly/README.md
  tekton/cronjobs/releases_azure/releases/add-pr-body-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/add-pr-body-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/add-team-members-nightly/README.md
  tekton/cronjobs/releases_azure/releases/add-team-members-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/add-team-members-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/chains-nightly/README.md
  tekton/cronjobs/releases_azure/releases/chains-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/chains-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/dashboard-nightly/README.md
  tekton/cronjobs/releases_azure/releases/dashboard-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/dashboard-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/nextcron.txt
  tekton/cronjobs/releases_azure/releases/operator-nightly/README.md
  tekton/cronjobs/releases_azure/releases/operator-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/operator-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/pipeline-nightly/README.md
  tekton/cronjobs/releases_azure/releases/pipeline-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/pipeline-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/pr-commenter-nightly/README.md
  tekton/cronjobs/releases_azure/releases/pr-commenter-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/pr-commenter-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/pr-status-updater-nightly/README.md
  tekton/cronjobs/releases_azure/releases/pr-status-updater-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/pr-status-updater-nightly/kustomization.yaml
  tekton/cronjobs/releases_azure/releases/triggers-nightly/README.md
  tekton/cronjobs/releases_azure/releases/triggers-nightly/cronjob.yaml
  tekton/cronjobs/releases_azure/releases/triggers-nightly/kustomization.yaml
Labels: lgtm, approved, size/L, kind/cleanup
