Repository tektoncd/plumbing, pull requests merged in 2025-10, with the labels that each got.

#2851 Fix dashboard patch for external logs
  tekton/cd/dashboard/overlays/oci-ci-cd/kustomization.yaml
  tekton/cd/dashboard/overlays/oci-ci-cd/tekton-dashboard-deployment.yaml
Labels: lgtm, approved, size/S, kind/misc

#2855 Update the ko image to pull in go > 1.23
  tekton/catalog/tasks/publish.yaml
  tekton/ci/cluster-interceptors/build-id/tekton/README.md
  tekton/ci/cluster-interceptors/build-id/tekton/kustomization.yaml
  tekton/ci/cluster-interceptors/build-id/tekton/publish.yaml
  tekton/ci/cluster-interceptors/build-id/tekton/release-pipeline.yaml
Labels: lgtm, approved, size/L, kind/misc

#2857 Small fixes to get the CI webhook running
  tekton/cd/add-pr-body-ci/overlays/oci-ci-cd/kustomization.yaml
  tekton/ci/bases/trigger.yaml
  tekton/ci/cluster-interceptors/add-pr-body/config/interceptor-deployment.yaml
  tekton/ci/infra/ingress.yaml
Labels: lgtm, approved, size/S, kind/misc

#2706 tekton/ci: remove plumbing-image-build.
  tekton/ci/jobs/kustomization.yaml
  tekton/ci/jobs/tekton-image-build.yaml
  tekton/ci/repos/plumbing/kustomization.yaml
  tekton/ci/repos/plumbing/template.yaml
Labels: lgtm, approved, size/L, kind/misc

#2863 Fix the add-pr-body-ci input
  tekton/ci/bases/trigger.yaml
  tekton/ci/jobs/e2e-kind.yaml
  tekton/ci/jobs/tekton-golang-coverage.yaml
Labels: lgtm, approved, size/XS

#2864 Further fix add-pr-body
  tekton/ci/bases/trigger.yaml
  tekton/ci/cluster-interceptors/add-pr-body/README.md
  tekton/ci/cluster-interceptors/add-pr-body/pkg/pr.go
  tekton/ci/cluster-interceptors/add-pr-body/pkg/pr_test.go
Labels: lgtm, approved, size/S, kind/misc

#2867 Update the version of add-pr-body
  tekton/cd/add-pr-body-ci/base/kustomization.yaml
Labels: lgtm, approved, size/XS, kind/misc

#2882 Consolidate prow config, restore pruner
  prow/config.yaml
  prow/ghproxy.yaml
  prow/ingress.yaml
  prow/kustomization.yaml
  prow/oci-bv-ssd-retain_storageclass.yaml
  prow/oci/kustomization.yaml
  prow/plugins.yaml
Labels: lgtm, approved, size/L, kind/misc
